### ISSUE TITLE
Forwarding header

### ISSUE THREAD

**Issue by sasq64** [yhirose/cpp-peglib#104]
Compiling a unit that includes the peglib headers takes quite some time.

It should not be too hard to create a forwarding header, maybe by just defining some macro
before including the normal header, to avoid the recompilation time when developing a grammar?

**Comment by yhirose** [comment]
@sasq64, thanks for the feedback. Yes, it takes long time to compile peglib since it is a single file header-only library.

Could you explain your idea more clearly? Unless peglib.h is still a single file, I am ok to implement your idea in peglib.h. Thanks!

**Comment by sasq64** [comment]
You can look at _catch.hpp_ for instance; You define `CATCH_CONFIG_MAIN` only in one translation unit to get the full implementation, and in other units you can include the file more cheaply since it only defines forwarding functions/classes.

In your case I guess you should do the reverse, a define like `FORWARDING_ONLY` that makes the header only forward declare the things you need, I guess at least  create a parser and add semantic actions.

BTW I've only just started using this library but it's great so far and I really love the PEG Playground :)

**Comment by sasq64** [comment]
I could see that this would be pretty hard to do, even if it should be possible.

Instead I created "wrapper" versions of `parser` and `SemanticValues` that contains the real implementations but can live in another translation unit. This helped compilation times.

**Comment by yhirose** [comment]
@sasq64, thanks for the info. I'll close it since you found the solution and I can go with the current code.
