### ISSUE TITLE
Enter / Leave methods

### ISSUE THREAD

**Issue by sasq64** [yhirose/cpp-peglib#108]
I am not sure I understand how these methods work.

I want to know if I am inside another Rule, so I add enter/leave to a parent rule, but usually
enter() and leave() are called right after each other, and _then_ the actions for the rules deeper down?

**Comment by sasq64** [comment]
So in my case; Is there any way of knowing if your are "inside" (a child of) another rule short of creating an AST ?

**Comment by yhirose** [comment]
> I want to know if I am inside another Rule, so I add enter/leave to a parent rule, but usually
enter() and leave() are called right after each other, and then the actions for the rules deeper down?

You are right.

> So in my case; Is there any way of knowing if your are "inside" (a child of) another rule short of creating an AST ?

cpp-peglib doesn't support it. Sorry about that.

You can see an example in the following unit test:

https://github.com/yhirose/cpp-peglib/blob/4b2545801205cca6b6d74bbf1829ee2deb71585f/test/test1.cc#L210-L253

Hope it help!
