### ISSUE TITLE
Macro that passes args to another macro causes crash?

### ISSUE THREAD

**Issue by stephenwhittle** [yhirose/cpp-peglib#109]
The following grammar causes the Playground to give `function signature mismatch`. native Peglib also crashes with a vector index out of bounds error in a test application compiled with MSVC.  

> SCPTable <- NamedTableSection('TestVal1', 'TestVal2')+
> NamedHeader(HeaderName) <- '#' HeaderName
> NamedTableSection(SectionName, ObjectName) <- NamedHeader(SectionName) '#End'
> %whitespace <- [ \t\r\n]*

My original grammar is more complex than this (for instance, `ObjectName` is being passed to a second macro after `NamedHeader`) but this is the minimal reproduction. 

Replacing `SectionName` on the right hand side with the literal value 'test' makes the issue go away. 

Callstack for native:

> peg::FindReference::visit() Line 2880
> peg::Reference::accept() Line 2755
> peg::Reference::parse_core() Line 2600	

Playground console output:

> native.wasm:1 Uncaught RuntimeError: function signature mismatch
>     at wasm-function[50]:0x465e

**Comment by yhirose** [comment]
@stephenwhittle, thanks for finding the serious bug in macro! I fixed it. Please let me know if the fix doesn't solve the problem in your code.
