### ISSUE TITLE
Only support C++17

### ISSUE THREAD

**Issue by yhirose** [yhirose/cpp-peglib#110]
It can reduce lots of lines, and improve performance with `std::string_view`.

**Comment by pdhahn** [comment]
I respectfully request you continue to allow C++11. I am not ready to move my compiler versions up(!) and my guess is there are others in the same situation. Maybe incorporate preprocessor code that detects C++17 if possible, enabling improvements within cpp-peglib at compile time based on whether the compiler supports C++17 (is that possible?).

**Comment by yhirose** [comment]
@pdhahn, don't worry about it. I am not going to move to C+17 anytime soon. This is just a reminder for me.  😄 

The main reason of switching C++17 is to improve performance with `std::string_view`, as well as to drop unnecessary code such as `peg::any` class and the weird code for old compilers support.

**Comment by yhirose** [comment]
@pdhahn, my workplace completely moved to C++17 build environment, and I now have to get rid of old stuff such as `peg::any`, and make performance improvement with `std::strintg_view`. So please prepare your code base to be C++17 compatible soon. My plan is to finish it by the end of this year. Hope your transition will go smoothly as well!

**Comment by yhirose** [comment]
#81

**Comment by pdhahn** [comment]
@yhirose Thanks for the heads up -- I appreciate it! Would you please be sure to tag the final pre-C++17 version in the repository, or maybe put it on a separate branch?

**Comment by yhirose** [comment]
@pdhahn, I uploaded [cpp17 branch](https://github.com/yhirose/cpp-peglib/tree/cpp17) for your reference. One of the change is that `std::string_view` is widely used in this library instead of `std::string`, so that we could avoid unnecessary memory copy very much. Also it uses the C++17 `std::any`.

I am supposed to merge it to the master branch sometime this month. At the same time, I'll make `cpp11` branch where I may commit bug fixes.

**Comment by sasq64** [comment]
Will you also make `name` and `original_name` in nodes and semantic values string_views, and reference into the grammar ?

I am asking because I want to serialize/cache the generated AST and it's easier if there are just offsets & sizes that needs to be written (along with the full source).

**Comment by yhirose** [comment]
@sasq64, no. It's because `name` and `original_name` have nothing to do with source text. These are definition names that come from definition names in a `parser` object.

**Comment by yhirose** [comment]
Done.

**Comment by Username404-59** [comment]
So C++20 isn't supported?
