### ISSUE TITLE
Pthread is not linked on Ubuntu

### ISSUE THREAD

**Issue by sasq64** [yhirose/cpp-peglib#111]
`system_error` in `peglib.h:2323` /  `mutex:697` (destroyed mutex?)

EDIT: Grammar removed, happens on any grammar.

Ubuntu 20.04 / GCC 9.3.0

**Comment by yhirose** [comment]
@sasq64, thanks for the feedback, but  I don't experience such a problem at all. Could you give me more detailed information?

**Comment by sasq64** [comment]
```
$ mkdir build ; cd build ; cmake .. ; make
$ echo "Root <- 'a'" > grammar.peg
$ lint/peglint grammar.peg
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
[1]    46594 abort (core dumped)  lint/peglint grammar.peg
$ c++ --version
$ c++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
$
```

**Comment by sasq64** [comment]
Maybe pthead doesn't get linked for some reason ?

**Comment by yhirose** [comment]
@sasq64, thanks for catching that. Could you try to add `set(add_link_deps Threads::Threads)` in lint/CMakeLists.txt for now. When I have time, I'll fix it.

**Comment by yhirose** [comment]
@sasq64, @XinzhaoZHU, I confirmed that the pull request #105 causes the problem. I am thinking to revert it, so that Ubuntu build will work again.
