### ISSUE TITLE
Writing a rule for function call

### ISSUE THREAD

**Issue by Beedeebee** [yhirose/cpp-peglib#115]
I'm trying to write a grammar for a micro-language that includes function calls.

A function should be able to return a function, thus something like the following should be allowed syntax:

```
// Call function f. It returns a function f'=f().
// Call function f'. It returns a function. f''=f'()=f()()
// Call function f''.
f()()();
```

I am not able to write a rule for a function call without using left-recursion.

Is there any way?

**Comment by Beedeebee** [comment]
I looked at #39 and at PEG.js, linked in that issue.

[PEG.js javascript grammar](https://github.com/pegjs/pegjs/blob/master/examples/javascript.pegjs) is able to parse `f()()()` as:

```
"type":"CallExpression", "arguments":[], "callee":{
	"type":"CallExpression", "arguments":[], "callee":{
		"type":"CallExpression", "arguments":[], "callee":{
			"type":"Identifier", "name":"f"
		}
	}
}
```

However I wasn't able to understand how they can parse that or whether they really support left recursion.

**Comment by yhirose** [comment]
@Beedeebee, thanks for the feedback. You don't need the left recursion to support the syntax. The following is the PEG.js grammar which does the above parsing:

https://github.com/pegjs/pegjs/blob/b7b87ea8aeeaa1caf096e2da99fd95a971890ca1/examples/javascript.pegjs#L631-L662

My script language supports it in the following grammar without left recursion:
https://github.com/yhirose/culebra/blob/05977a0ad9b5fddcf6a2320f0d551a5cf84b86bd/misc/culebra.peg#L22

Hope it helps!

**Comment by Beedeebee** [comment]
Thanks for showing me how to implement this thing!

I'm unable to understand Peg.js syntax. I'll try to learn it.

But I could see that the idea in culebra is treating "multiple" function calls as a sequence, rather than recursively. I'll transform the sequence back into a recursive AST node later.
