### ISSUE TITLE
Using a custom AST node type is broken

### ISSUE THREAD

**Issue by peoro** [yhirose/cpp-peglib#116]
Using a custom AST node type is broken in the latest versions.

That's because `peg::parser::enable_ast<T>` calls `peg::add_ast_action` (i.e. `peg::add_ast_action<peg::Ast>`) instead of `peg::add_ast_action<T>`, in [peglib.h:3940](https://github.com/yhirose/cpp-peglib/blob/c49366ad07444e8c58dae58716c990eba60823c9/peglib.h#L3940).

**Comment by yhirose** [comment]
@peoro, thanks for catching the bug, and sent a pull request to fix it!
