### ISSUE TITLE
compiling with  -Woverloaded-virtual fails

### ISSUE THREAD

**Issue by xmaton** [yhirose/cpp-peglib#118]
We compile our project with -Woverloaded-virtual and when I try to include the peglib it fails to compile:

```
In file included from ../main.cpp:20:
.././peglib.h:1722:16: error: ‘virtual void peg::Ope::Visitor::visit(peg::PrecedenceClimbing&)’ was hidden [-Werror=overloaded-virtual]
 1722 |   virtual void visit(PrecedenceClimbing & /*ope*/) {}
      |                ^~~~~
.././peglib.h:1726:8: error:   by ‘virtual void peg::IsReference::visit(peg::Reference&)’ [-Werror=overloaded-virtual]
 1726 |   void visit(Reference & /*ope*/) override { is_reference = true; }
      |        ^~~~~
.
.
.
many more errors
```

It seems that basically anything that derives from `Ope::Visitor` should either override all virtual functions from the base class or import wholesale the base implementation by `using Ope::Visitor::visit;` in every visitor.
Do you have any preference which way to fix the problem?

**Comment by yhirose** [comment]
@xmaton, thanks for the report!

**Comment by xmaton** [comment]
Thank you very much for the quick fix!
Can you also cut a fresh release relative soon so we can sync up to a nice tag (0.1.12 or something).

Thanks again!

**Comment by yhirose** [comment]
@xmaton, I just bumped up the version number. Hope your project goes well!

**Comment by xmaton** [comment]
Excellent! Thanks!
