### ISSUE TITLE
hyphen ('-') handling issue

### ISSUE THREAD

**Issue by elivermeulen** [yhirose/cpp-peglib#120]
The following grammar treats the hyphen differently than the underscore, not sure why.

rule <- [a-z'-''_']+

aa_aa => ok
aa-aa => not ok

Removing the single quotes seems to resolve the issue, but that approach is not applicable for all characters.

**Comment by yhirose** [comment]
@elivermeulen, if it means you want 'a' through 'z' and '-' and '_', it should be be `rule <- [a-z_-]+`. Hope it helps!

**Comment by elivermeulen** [comment]
@yhirose , I did try this, but the online version gives a syntax error on that rule.

**Comment by yhirose** [comment]
@elivermeulen, it should be `rule <- [a-z-_]+`. Sorry about that...

![image](https://user-images.githubusercontent.com/357397/86361006-336e8a80-bc41-11ea-8e68-df7cf55ca984.png)
