### ISSUE TITLE
create sample grammar for C language (or subset thereof) similar to 'picoc'

### ISSUE THREAD

**Issue by pdhahn** [yhirose/cpp-peglib#129]
If you ever have nothing to do (!), please consider creating a sample, functioning cpp-peglib grammar for C (or a nontrivial and meaningful subset thereof). This would include an interpreter.

At least in terms of C language support, this could be something similar to 'picoc', for example. See [https://github.com/jpoirier/picoc](url).

I think many people would find it highly useful as a starting point for their own extensions or completions, who previously valued cpp-peglib but were disinclined to start writing such a grammar from scratch, or who did not want to (say) modify or extend picoc's lex/parse mechanisms.

**Comment by yhirose** [comment]
@pdhahn, thanks for the feedback. It's an interesting idea. I don't have time to do so at this point. Of course you are welcome to submit a pull request at any time!

P.S. I am currently working on implementing 'Monkey Programming Language compiler' based on [Writing A Complier In Go]https://compilerbook.com/) with peglib.h in my spare time.
