### ISSUE TITLE
Playground is down

### ISSUE THREAD

**Issue by siy** [yhirose/cpp-peglib#133]
If to try to load [playgrund[(https://yhirose.github.io/cpp-peglib/), it waits forever and does not load :( 
The `wget -c https://yhirose.github.io/cpp-peglib/` works fine and loads the index.html, but text areas don't appear in the browser.

**Comment by yhirose** [comment]
@siy, thanks for the report. It seems like your grammar or source code choked the page... (This is not your problem, but may be a bug in peglib. I would like to know your grammar and source code which ended up falling in to the infinite loop.)

Could you clear the following local storage properties, and try again? Thanks for your help!

![image](https://user-images.githubusercontent.com/357397/103772594-c543bf80-4ff7-11eb-829f-b9c5e4462dbe.png)

**Comment by siy** [comment]
Unfortunately, to access those keys the site should be working, but it died again. I've tried to clear browsing data but not sure it will help.
By the way, it would be very convenient to have the ability to deploy the playground locally. I'd really appreciate if you publish necessary data and instructions to do this.

**Comment by yhirose** [comment]
@siy, you can launch the local PEG playground very easily because it's just a static web application with wasm version of cpp-peglib parser. (In other words, the github server wasn't actually down, rather the wasm peg parser  on the page got frozen with certain PEG grammar.)

Here is the steps:

```bash
cd docs
python3 -m http.server
```

That's it! Then you will play on http://localhost:8000/ on your browser.

Please let me know when you find the cause of this problem. I'll try to reproduce it on my machine and fix it.
Thanks!

**Comment by siy** [comment]
It took some time to reproduce the issue, but seems the situation when it hangs looks like this:
In the 'Grammar' and 'Source code' text areas present a grammar and test code respectively, both are marked by 'Valid' banner. Then in the 'Grammar' I choose the rule like ' A <- B / C ' and type '/' and ' ' (space) next to existing '/', so the whole rule starts looking like 'A <- B / / C'. At this point everything hangs. Hang with online version of playground was under exactly the same conditions.

**Comment by yhirose** [comment]
@siy, I followed your explanation, but it doesn't make any serious problem. (It of course gives syntax errors like `1:12 'C' is not defined.` and `1:6 'B' is not defined.`. But they are expected.) I probably don't fully understand what 'I choose' means...

Could you show exact steps more clearly, so that I can reproduce the problem on the playground?
Thanks for your help!

**Comment by siy** [comment]
Precondition: Chrome Version 87.0.4280.141 (Official Build) snap (64-bit), Linux.
 
Content for the "Grammar":
```
PROGRAM <- USES TYPES

USES <- USE*
USE <- _ 'use' PKG_NAME SEMICOLON
PKG_NAME <- NAME ('.' NAME )*

TYPES <- TYPE*
TYPE <- _ 'type' TYPE_NAME _ '=' (TYPE_NAME_DECL / FN_TYPE_DECL / ENUM_TYPE_DECL / API_TYPE_DECL / CLASS_TYPE_DECL)

TYPE_NAME_DECL <- TYPE_NAME SEMICOLON
TYPE_NAME <- NAME TYPE_PARAMS?
TYPE_PARAMS <- '<' TYPE_LIST '>'
TYPE_LIST <- TYPE_NAME (',' TYPE_NAME)*

FN_TYPE_DECL <- TYPE_LIST _ '->' TYPE_NAME SEMICOLON

ENUM_TYPE_DECL <- TYPE_NAME ( _ '|' TYPE_NAME )* ENUM_API

ENUM_API <- SEMICOLON / _ API_REF

API_REF <- ':' (TYPE_LIST)? (SEMICOLON / API_DECL_BODY)

API_TYPE_DECL <- _ 'api' API_DECL_BODY
API_DECL <- _ 'api' TYPE_NAME API_DECL_BODY

API_DECL_BODY <- BLOCK_START (FN_DECL / STATICS / API_DECL / CLASS_DECL)* BLOCK_END

CLASS_TYPE_DECL <- _ 'class' CLASS_DECL_BODY
CLASS_DECL <- _ 'class' TYPE_NAME CLASS_DECL_BODY
CLASS_DECL_BODY <- DATA_DECL? BLOCK_START (FN_IMPL / STATICS / API_DECL / CLASS_DECL)* BLOCK_END
DATA_DECL <- _ '(' TYPED_ARG_LIST ')'

FN_DECL <- FN_DECL_TITLE SEMICOLON
FN_DECL_TITLE <- TYPE_VARS_DECL? TYPE_NAME NAME '(' _ TYPED_ARG_LIST? ')'
FN_IMPL <- (FN_DECL_TITLE / FN_IMPL_TITLE) (FN_VAR_ASGN / FN_IMPL_SCRIPT)
FN_IMPL_TITLE <- _ 'impl' NAME '(' NAME_LIST ')'
FN_IMPL_SCRIPT <- BLOCK_START (FN_VAR_DECL / FN_VAR_ASGN / FN_EXPR)* BLOCK_END

FN_VAR_DECL <- _ ('var' / 'val' / TYPE_NAME) NAME FN_VAR_ASGN
FN_VAR_ASGN <- _ '=' FN_EXPR
FN_EXPR <- EXPR SEMICOLON

STATICS <- _ 'const' TYPE_VARS_DECL? FN_VAR_DECL / _ 'static' FN_IMPL

TYPE_VARS_DECL <- _ '<' NAME_LIST '>'

TYPED_ARG_LIST <- TYPED_ARG ( ',' TYPED_ARG )*
TYPED_ARG <- TYPE_NAME NAME
NAME_LIST <- NAME (',' NAME)*

#temporary
EXPR <- NAME ( _ '(' EXPR_LIST? ')' )?
EXPR_LIST <- EXPR (',' EXPR)*

BLOCK_START <- _ '{' _
BLOCK_END <- _ '}' _
NUMBER <- _ < [0-9]+ > _
NAME <- _ < [_a-zA-Z] [a-zA-Z0-9]* > _
SEMICOLON <- _ ';'_

~_ <- [ \t\r\n]* COMMENT?

COMMENT <- '//' (!END .)* &END _?
END <- EOL / EOF
EOL <- '\r\n' / '\n' / '\r'
EOF <- !.
```
Content for the "Source Code"
```
type FN<T,R> = T->R;

type Option<T> = Just<T> | Nothing<T> : {
    // Full type annotations
    <R> Option<R> map(FN<T, R> mapper);
    <R> Option<R> flatMap(FN<T, Option<R>> mapper);
    
    // Shorter form
    Option<R> map(FN<T, R> mapper);
    Option<R> flatMap(FN<T, Option<R>> mapper);

    // Full type annotation
    static <T> Option<T> option(T value) = Just(value);
    // Shorter form
    static Option option(T value) = Just(value);
    static Option empty() = NONE;

    //Polymorphic constant
    const Option<_> NONE = Nothing();
    
    class Just<T> (T value) {
        impl map(mapper) = Just(mapper(value));
        impl flatMap(mapper) = mapper(value);
    }
    
    class Nothing<_> {
        impl map(mapper) = this;
        impl flatMap(mapper) = this;
    }
}
```
Now go to line 30 (CLASS_DECL_BODY rule) and move cursor right after 'API_DECL' term and type Space followed by '/'. 
Once you type '/', the page freezes completely. Since data stored in local storage, reloading does not help. The only solution is to clear site data, but this means loss of all changes.

**Comment by yhirose** [comment]
@siy, great! I was able to break down the problem based on your example. Here is the simplest code to reproduce it.

```peg
S <- '{' ('A' // 'B')* '}' [ \n]*
```

```txt
{A}
```

This is obviously a bug that I didn't notice before. I guess the PEG grammar `//` should be reported as an error. Also, even if such an invalid grammar is given, a PEG parser shouldn't get into an infinite loop at least...

Sorry for causing you such an inconvenience for now. I'll look into the problem sometime soon, and get back to you.
Thanks a lot!

**Comment by yhirose** [comment]
@siy, I think I fixed it. The grammar no longer cause the infinite loop on my machine. Could you also confirm it with the latest peglib.h on the master branch? If it works on your machine, then I'll bump up the version number of cpp-peglib.
Thank you

**Comment by siy** [comment]
It works fine for me too. Thanks for a great project and wonderful support!

**Comment by yhirose** [comment]
@siy, v1.0.1 including this fix is out. Thanks for your contribution!
