### ISSUE TITLE
Ability to start parsing from specified rule

### ISSUE THREAD

**Issue by siy** [yhirose/cpp-peglib#135]
Sometimes it's necessary to reparse input from given point. For example this happens in interactive apps which analyse input as user types it. If whole input is rather big, then parsing from scratch could be too time consuming. Instead it's possible to find nearest outer node in AST and reparse only changed part of the input. For this use case it would be convenient to restart parsing from the given rule.

**Comment by yhirose** [comment]
@siy, thanks for the feedback. I probably don't fully understand what you actually want to do. Could you send me a pull request for the feature? The start rule name is kept in `start_` in `class parser`. If you can manage it properly, it may be possible to start parsing from some rules rather than the first specified rule in a given grammar. I am not 100% sure that it can be really possible though, it would be nice to give it a try. Thanks!

**Comment by siy** [comment]
The use case can be modelled, for example, using PL/0 grammar. Let's imagine that we have loaded and parsed some PL/0 source file and showing it in the editor. Then the user modifies some code inside a nested BEGIN - END block somewhere deep inside the PROCEDURE. To parse changed code we need either parse everything from scratch using full grammar or find the outer rule (in this case it will be 'statements' rule) and parse code only inside the modified BEGIN - END block.

I'll definitely try to experiment with this and if my experiments will be successful, I'll submit a PR.

**Comment by yhirose** [comment]
@siy, do you think if the following change is enough for what you are trying to do?

```cpp
class parser {
public:
  ...
  void set_start_rule(std::string_view rule) {
    start_ = rule;
  }
```

**Comment by yhirose** [comment]
@siy, I'll close it for now since I am not planning to implement this feature.

**Comment by Krzmbrzl** [comment]
@yhirose I would very much appreciate having a `set_start_rule` function available. Right now, it seems like we have to use `load_grammar` every time we want to change the start rule, which seems overkill (as the grammar never changes). Is there anything specific that speaks against adding this function?

**Comment by yhirose** [comment]
@Krzmbrzl, thank you for the feedback! I have already carefully considered the possibility of adding a `set_start_rule` method or a start rule parameter to parse. However, such a runtime start rule changer could cause some serious issues. That’s why I decided to handle it with `load_grammar`. Please see https://github.com/yhirose/cpp-peglib/issues/304.

This issue explains the problems with `whitespaceOpe` and `wordOpe`, but those are just two examples. There are also others—such as `ignoreSemanticValue`, `eoi_check`, `enablePackratParsing`, `tracer_enter`, `tracer_leave`, `tracer_start`, `tracer_end`, and `verbose_trace`—that also need to be addressed. I may add more such member variables in the future, and we would need to handle those as well.

Therefore, my conclusion is to allow setting the start rule only when constructing a grammar.
