### ISSUE TITLE
from_chars() is not implemented in some C++17 compilers

### ISSUE THREAD

**Issue by yesint** [yhirose/cpp-peglib#136]
I've come across an issue with gcc 9.3, which is now the default compiler in Ubuntu and derived linuxes. Apparently, it doesn't implement C++17 completely and the call to `from_chars<float>()` produces errors:
```
peglib.h:3688: error: no matching function for call to ‘from_chars(std::basic_string_view<char>::const_pointer, std::basic_string_view<char>::const_pointer, float&)’
 3688 |     std::from_chars(token.data(), token.data() + token.size(), n);
      |     ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Is it possible to put a list of major compilers with full C++17 support in the docs to make it clear? Such errors are rather cryptic and it takes a lot of time to debug up to compiler incompatibility.

Is it also possible to put a direct link to the last peglib version which is still compatible with C++14?

**Comment by yhirose** [comment]
@yesint, thank you for the report. I don't have such a supported compilers list though, I can at least tell that it can be compiled with default compilers of ubuntu-20.04, macos-latest, windows-latest on GitHub Actions workflow. Please see the following:
https://github.com/yhirose/cpp-peglib/blob/1c00fa77fa23bca9f0eb6dc41d0360a135b6fd7a/.github/workflows/cmake.yml#L18

> Is it also possible to put a direct link to the last peglib version which is still compatible with C++14?
I made the [C++11 branch](https://github.com/yhirose/cpp-peglib/tree/cpp11) when I release the current C++17 version. It should be compiled with C++11 and C++14 compilers. It is already missing a number of bug fixes and enhancements that are only available on the master branch.

If `std::form_chars` is only place that gcc 9.3 complains at, I am ok to replace it with something else, since gcc 9.3 is still a pretty recent compiler. Please let me know your thought. Thanks!

**Comment by yesint** [comment]
@yhirose, thank you for fast reply!
So far `std::form_chars` is the only offending place in gcc 9.3 in my project.
I completely understand that maintaining two versions up to date is boring and time consuming. Unfortunately, support of the `string_view`-related features in different compilers is still pretty much random, while many production systems, such as computational clusters, often have rather old tool-chains. Thus C++11 branch is great to have for the coming few years at least.

Thanks for fantastic library!

**Comment by yhirose** [comment]
@yesint, I tried to reproduce it with gcc 9.3, but I couldn't... Could you give me more information?
Here is the screenshot of my experiment:

![image](https://user-images.githubusercontent.com/357397/105182948-a36c3180-5afb-11eb-8bb3-737074465604.png)

**Comment by yesint** [comment]
@yhirose, it only crashes if `from_chars<float>()` is called somewhere (only with `float`, `int` is Ok). In your code it's not called.

See this minimal example:

```
$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

semen@semen-home-desktop ~/work/stored/temp/m $ cat a.cpp 
#include <charconv>
#include <iostream>
#include <string_view>

int main()
{
 float result;
 std::string_view sv{"24 abc "};
 std::from_chars(sv.begin(), sv.end(), result);
}

semen@semen-home-desktop ~/work/stored/temp/m $ g++ -std=c++17 a.cpp 

a.cpp: In function ‘int main()’:
a.cpp:9:46: error: no matching function for call to ‘from_chars(std::basic_string_view<char>::const_iterator, std::basic_string_view<char>::const_iterator, float&)’
    9 |  std::from_chars(sv.begin(), sv.end(), result);
      |                                              ^
In file included from a.cpp:1:
/usr/include/c++/9/charconv:600:5: note: candidate: ‘template<class _Tp> std::__detail::__integer_from_chars_result_type<_Tp> std::from_chars(const char*, const char*, _Tp&, int)’
  600 |     from_chars(const char* __first, const char* __last, _Tp& __value,
      |     ^~~~~~~~~~
/usr/include/c++/9/charconv:600:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/9/charconv:36,
                 from a.cpp:1:
/usr/include/c++/9/type_traits: In substitution of ‘template<bool _Cond, class _Tp> using enable_if_t = typename std::enable_if::type [with bool _Cond = std::integral_constant<bool, false>::value; _Tp = std::from_chars_result]’:
/usr/include/c++/9/charconv:592:11:   required by substitution of ‘template<class _Tp> using __integer_from_chars_result_type = std::enable_if_t<std::__and_<std::is_integral<_Tp>, std::__not_<std::__or_<std::is_same<_Tp, bool>, std::is_same<_Tp, char16_t>, std::is_same<_Tp, char32_t>, std::is_same<_Tp, wchar_t> > > >::value, std::from_chars_result> [with _Tp = float]’
/usr/include/c++/9/charconv:600:5:   required by substitution of ‘template<class _Tp> std::__detail::__integer_from_chars_result_type<_Tp> std::from_chars(const char*, const char*, _Tp&, int) [with _Tp = float]’
a.cpp:9:46:   required from here
/usr/include/c++/9/type_traits:2385:11: error: no type named ‘type’ in ‘struct std::enable_if<false, std::from_chars_result>’
 2385 |     using enable_if_t = typename enable_if<_Cond, _Tp>::type;
      |           ^~~~~~~~~~~

```

**Comment by yesint** [comment]
For me it was crashing when using `token_to_number<float>()` in the AST transformation code.

**Comment by yhirose** [comment]
@yesint, thanks for the info. I'll try to make a fallback function for the float, double and long double versions of std::from_chars;
It seems this is a very good article regarding it: https://www.bfilipek.com/2019/07/detect-overload-from-chars.html#example-stdfromchars

**Comment by yhirose** [comment]
@yesint, I fixed it. The drawback of this fix is that it always uses own version of 'string to float/double/long double/' function based on `std::istringstream` even if a compiler supports `std::from_chars<float>, ...`. According to my research, `std::istringstream` version is slower than `std::from_chars`. So I put 'TODO' marks which indicate the changes should be removed in the future when gcc 9.x is considered as an 'old' compiler.
