### ISSUE TITLE
Tag 1.3.0 is incompatible with C++20

### ISSUE THREAD

**Issue by jordanvrtanoski** [yhirose/cpp-peglib#141]
I am using the library with C++20. Till 1.3.0, the library had worked fine. The introduction of the literal with the UTF8 in the 1.3.0 is throwing error. C++20 had changed the handling of the UTF8 characters.

In file included from parser/Parser.cpp:5:
In file included from parser/Parser.h:8:
cmake-build-debug/external_includes/cpp-peglib/peglib.h:3092:21: error: no matching function for call to 'lit'
    g["CUT"] <= seq(lit(u8"↑"), g["Spacing"]);
                    ^~~
cmake-build-debug/external_includes/cpp-peglib/peglib.h:1577:29: note: candidate function not viable: no known conversion from 'const char8_t [4]' to 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') for 1st argument
inline std::shared_ptr<Ope> lit(std::string &&s) {
                            ^
cmake-build-debug/external_includes/cpp-peglib/peglib.h:3093:38: error: no matching function for call to 'lit'
    ~g["LABEL"] <= seq(cho(chr('^'), lit(u8"⇑")), g["Spacing"]);
                                     ^~~
cmake-build-debug/external_includes/cpp-peglib/peglib.h:1577:29: note: candidate function not viable: no known conversion from 'const char8_t [4]' to 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') for 1st argument
inline std::shared_ptr<Ope> lit(std::string &&s) {
                            ^

**Comment by yhirose** [comment]
@jordanvrtanoski, thanks for the report. Could you check with the latest master code?
