### ISSUE TITLE
creating a dynamic parser

### ISSUE THREAD

**Issue by mqnc** [yhirose/cpp-peglib#149]
When I was working on my programming language years ago, I used lua to generate the grammar and the rules for the language dynamically (which allows the user to load language plugins). I fed the generated grammar into peglib and then used the resulting parser to transpile my custom language source files into c++.

However, this means, there are two levels: The generation of the language where the user can load language plugins which influence the syntax of the language itself (like custom infix operators) and then the actual transpilation of source level.

Now I am flirting with the idea of combining both these things. It is probably less practical and sane but way more adventurous and interesting :)

I tried if peglib can modify the parser while parsing and it looks good:
```cpp
Definition ROOT, A, B, X;
ROOT <= oom(cho(A, B, X));
A <= chr('1');
A = [&](const SemanticValues &vs) { std::cout << "a"; };
B <= chr('2');
B = [&](const SemanticValues &vs) { std::cout << "b"; };
X <= chr('x');
X = [&](const SemanticValues &vs) {
	std::cout << "x";
	A <= chr('2');
	A = [&](const SemanticValues &vs) { std::cout << "A"; };
	B <= chr('1');
	B = [&](const SemanticValues &vs) { std::cout << "B"; };
	X <= chr('X');
	X = [&](const SemanticValues &vs) { std::cout << "X"; };
};
auto ret = ROOT.parse("12x12X");
```
Output: `abxBAX`

The X rule even modified itself!

I am not asking whether this is a good idea or not (although this could even have practical applications with selective whitespace skipping), I would just like to know if this is technically feasible using peglib or whether this will somehow crash with its architecture and explode in the meanest possible way and with my experiment I just got lucky.

Imagine, we can have a parser which in the beginning only knows how to add new rules to itself and it grows while parsing the source code!

Another thing, if this works, can I also run sanity checks on the grammar similar to `ParserGenerator::perform_core` from inside the parser everytime it modified itself?

Cheers!

**Comment by yhirose** [comment]
> I would just like to know if this is technically feasible using peglib or whether this will somehow crash with its architecture

I am not sure exactly though, I think it's ok unless you use the packrat parsing mode.

> can I also run sanity checks on the grammar similar to ParserGenerator::perform_core from inside the parser every time it modified itself?

`ParserGenerator::perform_core` is only for making a parser from a PEG grammar text, not for a user defined parser with parser combinators. Since the parser combinators are very much limited in comparison, it don't think it's possible to apply what `ParserGenerator::perform_core` does to a parser with combinators. Sorry about that.

Hope the above answers help!
