### ISSUE TITLE
Improve %whitespace behavior

### ISSUE THREAD

**Issue by siy** [yhirose/cpp-peglib#150]
The %whitespace is a great feature which helps to keep grammar clean and tidy. Unfortunately it is not handled as a full parsing rule definition. For example, I was expecting that the following grammar will skip comments just like whitespace:
```
%whitespace <- [ \t\r\n]* / Comment*
Comment <- '//' (!end .)* &end
end <- eol / eof
eol <- '\r\n' / '\n' / '\r'
eof <- !.
```
Unfortunately for simple input like this:
```
// wefwfesd

```
It produces the following error:
```
1:1 syntax error, unexpected '/', expecting <%whitespace>.
```
Would be great if %whitespace behaved like full rule and consumed comments as whitespace. Also, this would enable attaching a semantic action to the "%whitespace" and obtain a convenient way to process comments (for example, generate documentation) and do this independently of other actions.

**Comment by yhirose** [comment]
@siy, could you explain what 'full rule' means?

**Comment by siy** [comment]
My bad, definition for %whitespace is just incorrect.
