### ISSUE TITLE
Ast should be explicitly marked as non-copyable

### ISSUE THREAD

**Issue by yesint** [yhirose/cpp-peglib#153]
Since Ast objects now utilize string_view internally, they should be non-copyable by design. The nodes of the copy of Ast object will point their string_views to the parse string of original object. If original is destroyed one ends up with dangling pointers and ugly bugs, which are extremely hard to find. This is even worse because in older versions of peglib Ast was copyable, which introduces nasty bugs into the old code.
Marking copy constructor and assignment operator of Ast as deleted will fix this.

**Comment by yhirose** [comment]
@yesint (and cc to @toddlipcon), good point! could you send me a pull request?

**Comment by yesint** [comment]
The problem is that I'm not very familiar with peglib internals, so dumb adding of 
```
AstBase(const AstBase&) = delete; // non construction-copyable
AstBase& operator=(const AstBase&) = delete; // non assignable
```
doesn't work. The `shared_ptr<Ast>` requires Ast to be default copy-constructible as far as I understand.
However, deleting assignment operator works fine.

For copy-constructor I can only come up with run-time check, which throws an exception if attempted to copy-construct non-empty Ast:

```
AstBase(const AstBase& other):
      path(other.path),
      line(other.line),
      column(other.column),
      name(other.name),
      position(other.position),
      length(other.length),
      choice_count(other.choice_count),
      choice(other.choice),
      original_choice_count(other.original_choice_count),
      original_choice(other.original_choice),
      tag(other.tag),
      original_tag(other.original_tag),
      is_token(other.is_token),
      token(other.token)
  {
      if(!other.token.empty() || !other.nodes.empty() || other.parent.use_count()!=0)
          throw std::runtime_error("Can't copy-construct non-empty Ast node!");
  }
```

This is ugly. Could you possibly suggest any better solution?

**Comment by yhirose** [comment]
@yesint, yes, it's very dangerous to destroy the source text that the AST tree was generated from as you mentioned. But, it seems very hard to project this accidental destruction of the original source from users.

I am tending to leave the current code as it is, and put some meaningful document on README, so that users can clearly notice the danger. Sorry that I can't provide a safer solution...
