### ISSUE TITLE
peglib not a true superset of peg

### ISSUE THREAD

**Issue by mqnc** [yhirose/cpp-peglib#155]
The following grammar is valid in peg but not in peglib:
```
Start <- A(B)
A <- "a"
B <- "b"
```
I don't think this is ever going to bother anyone because it can just be solved by writing `A (B)` instead but still, it doesn't conform to the "standard" then, maybe that's important to you.

**Comment by yhirose** [comment]
@mqnc, you are correct. I sacrificed the notation without white space(s) for macro call...
