### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by vehlwn** [yhirose/cpp-peglib#156]
Hi,
I was testing your library (cpp-peglib/1.3.3) and found significant time degradation when parsing large texts.
Consider [this](https://github.com/vehlwn/json-peg-parser/blob/68f23caf64d3b9822d445455b083a8bd45d4165a/AstBuilder.cpp#L7) JSON grammar. (Note: my project depends on [conan](https://docs.conan.io/en/latest/introduction.html) for a cross platform packaging cpp-peglib an ICU for Unicode manipulations.). I varied input length in [here](https://github.com/vehlwn/json-peg-parser/blob/f7fdd78b9ca23f2ddc2d5125f6f5a675e16ba381/benchmark.cpp#L28) and it appears parsing takes `O(n**2)` time instead of `O(n)` stated in documents you mentioned in README.
Here is content of my times.txt:
```
1381	0.00860782
9381	0.0489359
17581	0.0529483
26581	0.0940859
35581	0.148088
44581	0.212408
53581	0.290591
62581	0.376676
71581	0.475748
80581	0.585969
89581	0.707752
98581	0.839846
107581	0.985527
116581	1.13869
125581	1.30703
134581	1.48065
143581	1.67072
152581	1.86825
161581	2.08091
170581	2.3155
179781	2.55577
189781	2.83595
199781	3.13142
209781	3.40987
219781	3.71165
229781	4.02243
239781	4.35569
249781	4.68124
259781	5.04414
269781	5.41115
279781	5.76695
289781	6.15295
299781	6.58493
309781	6.98621
319781	7.41164
329781	7.84023
339781	8.29442
349781	8.74905
359781	9.23535
369781	9.70401
379781	10.2583
389781	10.7753
399781	11.3677
409781	11.9708
419781	12.4558
429781	13.0259
439781	13.603
449781	14.203
459781	14.8071
469781	15.3889
479781	16.0697
489781	16.675
499781	17.3422
509781	18.0127
519781	18.6957
529781	19.3778
539781	20.0923
549781	20.805
559781	21.5239
569781	22.2533
```
First column is length in bytes. Second - time in seconds.
I approximated the data with gnuplot's `fit` command and get this least squares interpolant:
```
f1(x) = a2 * x**2 + a1 * x**1 + a0
fit f1(x) "times.txt" using 1:2 via a2, a1, a0

After 14 iterations the fit converged.
final sum of squares of residuals : 0.0527702
Final set of parameters            Asymptotic Standard Error
=======================            ==========================
a2              = 6.35096e-11      +/- 1.573e-13    (0.2476%)
a1              = 3.04542e-06      +/- 9.195e-08    (3.019%)
a0              = -0.0476503       +/- 0.0111       (23.29%)
```
When disabling `m_parser.enable_packrat_parsing();` in [here](https://github.com/vehlwn/json-peg-parser/blob/f7fdd78b9ca23f2ddc2d5125f6f5a675e16ba381/AstBuilder.cpp#L45) time's getting even worse.

I'm wondering what's the reason for this performance drop? Is your library designed for parsing large texts? For example, nlohmann_json runs in less a second for i = 29600; len = 569781 bytes.
Thanks in advance.
PNG image with my plots is in attachment.
![times-vehlwn](https://user-images.githubusercontent.com/36479428/110495197-b5d31680-810d-11eb-8054-e0847e3de5c7.png)

PS: [Here](https://drive.google.com/uc?id=1Y8-wqBdCN3ZJPnkqOpgQjki-dA8UFS7T) is an output of
`valgrind --tool=callgrind --dump-instr=yes --simulate-cache=yes --collect-jumps=yes ./bin/benchmark`
It shows `peg::Context::Context()` has the most Self time.
Screenshot is enclosed in attachment.
![latest-screenshot](https://user-images.githubusercontent.com/36479428/110499143-655db800-8111-11eb-9b46-d9ec8a626ce4.png)

**Comment by yhirose** [comment]
@vehlwn, thank you very much for the detailed report! It seems like I introduced the performance problem when I implemented word operator support...

I made some changes to peglib.h and made [a pull request](https://github.com/yhirose/cpp-peglib/pull/157). Could you try with [this version](https://github.com/yhirose/cpp-peglib/blob/issue156/peglib.h) to see how much the performance is inproved?

Thanks for your help!

**Comment by yhirose** [comment]
@vehlwn, thank you for the validation. I'll merge my pull request and include it in the next release version.

> Now it has linear time, but not as fast as nlohmann.

Yes, cpp-peglib can never beat dedicated parsers for specific purposes like nlohmann in performance. This library is mainly to help myself to make DSLs easier and quicker in my projects at work and personal projects. So if I would need parsers like  JSON, CSV, log file parsers which need parsing huge document with high performance, I would rather make a hand-written parser.

I implemented enhanced features like back reference, macro and so on in cpp-peglib, so that we can craft grammar easily with less lines and more readable code. But those additional features sacrifice performance... It's a trade-off between usability and performance. (If both can be achieved, that would be the best, of course!)

If your priority is performance, I recommend you to use such a dedicated JSON parser instead of cpp-peglib.

Thank you for your understanding!
