### ISSUE TITLE
Possible performance drop when checking infinite loops

### ISSUE THREAD

**Issue by jamoralp** [yhirose/cpp-peglib#158]
Good morning,

As you might now, in eProsima we are using your library as a base to construct our IDL parser in the [xtypes](https://github.com/eProsima/xtypes) library.

Right now, we are using a pretty much outdated version of the `peglib.h` file, and we wanted to take advantage of the new fixes and improvements that you have introduced, such as the improved error messages. We tried to update the library to the last version available, and our tests are working properly when executing them using plan CTest.

However, valgrind is behaving very strangely. Valgrind tests did not seem to pass and, in fact, we got the usual CTest timeout per test case (1500 seconds, 25 minutes) in tests that usually took about 3-4 minutes to get completed with valgrind. Very strange indeed.

I started to isolate the problem and, after many attempts, discovered that the commit that introduced this behaviour is https://github.com/yhirose/cpp-peglib/commit/ac602d5542af09c54c0bb9d073606f00964c7965. More specifically, the loop introduced in line 3567. If I revert this foor loop to what was done previously, this problem disappears and everything goes back to normal.
 
Is it possible that this single change is introducing so many computational overhead? Is there any way to """fix""" this? Which implications would have to just revert it to its previous state? Thank you a lot for your time.

**Comment by yhirose** [comment]
@jamoralp, thank you for the detailed report. It seems like it should be reverted. I'll check why I did it, then I'll get back to you.

**Comment by yhirose** [comment]
@jamoralp, I confirmed that unit tests at 82512d5002785604b456df4f9499050dc0996369 still pass even if I revert the change. Could you try with the latest peglib.h?

**Comment by jamoralp** [comment]
Tested and confirmed to be working now! Many thanks for the quick answer and fix :slightly_smiling_face:
