### ISSUE TITLE
Precedence climbing: Missing error message

### ISSUE THREAD

**Issue by kkayal** [yhirose/cpp-peglib#159]
There is an example for precedence climbing in the README.md file:

```
EXPRESSION             <-  INFIX_EXPRESSION(ATOM, OPERATOR)
ATOM                   <-  NUMBER / '(' EXPRESSION ')'
OPERATOR               <-  < [-+/*] >
NUMBER                 <-  < '-'? [0-9]+ >
%whitespace            <-  [ \t]*

# Declare order of precedence
INFIX_EXPRESSION(A, O) <-  A (O A)* {
  precedence
    L + -
    L * /
}
```

When I apply this grammar to the source code `2+3` I get the expected AST in the [PEG Playground](https://yhirose.github.io/cpp-peglib/).

However, when I remove the 3 and leave `2+` as the source code I would expect an error message, something like _"unexpected +"_ , but the PEG Playground doesn't mark this source code as invalid.

**Comment by yhirose** [comment]
@kkayal, thanks for the bug report!
