### ISSUE TITLE
possible meson subproject support

### ISSUE THREAD

**Issue by Apache-HB** [yhirose/cpp-peglib#165]
Currently consuming this project in a meson project is a bit cumbersome as it only supports cmake and doesnt expose the header file with `add_library` which [meson requires](https://mesonbuild.com/CMake-module.html#cmake-subprojects). Adding a meson build file would (in my opinion) bring value by allowing the project to be consumed as a meson subproject easily with little effort required to create and maintain the meson script.

**Comment by yhirose** [comment]
@Apache-HB, thanks for the feedback. I personally don't know anything about the build system. So I most likely won't be interested in the support in cpp-httplib project. But if you can support it with making a minimal change to the current CMakeLists.txt, I may accept the pull request. I'll close it for now. Thank you for your understanding.
