### ISSUE TITLE
Enforcing whitespace and infix

### ISSUE THREAD

**Issue by kkayal** [yhirose/cpp-peglib#166]
I am trying to express a grammar, which ignores white space in some places and enforces in others. That works fine unless I include infix expressions. Let me show it step by step:

Imagine the source code `var a = 2 + 3`. "var" is a keyword, "a" is an identifier and we have also an expression. The following grammar (lets call it 1) makes it work:

    init <- 'var' identifier '=' EXPRESSION
    
    identifier <- < alpha (alpha / digit)* >
    alpha   <- [A-Za-z_] # English letters and underscore
    digit   <- [0-9]
    
    EXPRESSION             <-  INFIX_EXPRESSION(ATOM, OPERATOR)
    ATOM                   <-  NUMBER / '(' EXPRESSION ')'
    OPERATOR               <-  < [-+/*] >
    NUMBER                 <-  < '-'? [0-9]+ >
    %whitespace            <-  [ \t]*
    
    # Declare order of precedence
    INFIX_EXPRESSION(A, O) <-  A (O A)* {
    precedence
      L + -
      L * /
    }

Now, this grammar also allows the source code `vara=2+3`. That is obviously not so good, so I try to enforce white space between the keyword `var` and the identifier `a`.

To achieve that, I add the rule `~space <- [ \t]+` and change the first line to `init <- 'var' space identifier '=' EXPRESSION`

So we get grammar 2:

    init <- 'var' space identifier '=' EXPRESSION
    
    identifier <- < alpha (alpha / digit)* >
    alpha   <- [A-Za-z_] # English letters and underscore
    digit   <- [0-9]
    
    EXPRESSION             <-  INFIX_EXPRESSION(ATOM, OPERATOR)
    ATOM                   <-  NUMBER / '(' EXPRESSION ')'
    OPERATOR               <-  < [-+/*] >
    NUMBER                 <-  < '-'? [0-9]+ >
    %whitespace            <-  [ \t]*
    
    # Declare order of precedence
    INFIX_EXPRESSION(A, O) <-  A (O A)* {
    precedence
      L + -
      L * /
    }

    ~space <- [ \t]+`

Now for the same source code `vara=2+3`, I get an error message in the PEG Playground saying

`1:4 syntax error, unexpected 'a', expecting <space>, <init>.`

So far so good. Now what happens when I insert a space between `var` and `a`? I was hoping that the source code would be valid, but unfortunately this is not the case. The new error message is exactly the same except that the position 1:4 becomes 1:5.

I guess the reason is the whitespace rule `%whitespace            <-  [ \t]*`. Perhaps this rule consumes the space between `var` and `a` first, so that I end up with the same error message.

Well I thought the straight forward solution is to remove that automatic white space rule. And as soon as I remove it in the PEG Playground, voilà, the source code validates.

The only problem left is that I don't know how to allow white space within the expression such as `2 +3`. Is there a way to apply the white space rule only to the infix expression rule?

**Comment by yhirose** [comment]
@kkayal, the real solution for this problem is to use `%word` rule.

```
init <- 'var' identifier '=' EXPRESSION

identifier <- < alpha (alpha / digit)* >
alpha   <- [A-Za-z_] # English letters and underscore
digit   <- [0-9]

EXPRESSION             <-  INFIX_EXPRESSION(ATOM, OPERATOR)
ATOM                   <-  NUMBER / '(' EXPRESSION ')'
OPERATOR               <-  < [-+/*] >
NUMBER                 <-  < '-'? [0-9]+ >
%whitespace            <-  [ \t]*
%word                  <-  [a-z]+ # or just `[a-z]` is fine

# Declare order of precedence
INFIX_EXPRESSION(A, O) <-  A (O A)* {
precedence
  L + -
  L * /
}
```

Also you can see another solution without using cpp-peglib's enhanced rules in [this PL/0 grammar example](https://github.com/yhirose/cpp-peglib/blob/master/grammar/pl0.peg).

Hope it helps.

**Comment by kkayal** [comment]
@yhirose Yes that works and thanks for the speedy reply!

**Comment by yhirose** [comment]
@kkayal, my example has a problem. It doesn't work with `varA=2+3` or `var_=2+3`.  So `%word` should be `%word <- alpha`... Sorry about that.

Although `%whitespace` and `%word` are convenient, they are not 'silver bullets' that can apply to all the situations. So if token rules are very complex, we may not able to use the enhanced rules and handle the situation manually.

Thanks for your interest in this library!

**Comment by kkayal** [comment]
Thanks, I am learning by doing;-) So far, I have created a simple tab separated values to markdown [converter](https://github.com/kkayal/tsv) using your library. Now I am trying more complicated things and will do so based on your PL0 example.

By the way, do you consider to activate Github's "Discussions" feature? The advantage would be to move questions like this one away from the "issues".
