### ISSUE TITLE
1.3.7: compilation fails with clang 6, 7, 10 & 11 on Linux

### ISSUE THREAD

**Issue by SpaceIm** [yhirose/cpp-peglib#167]
I tried to bump cpp-peglib from 1.3.5 to 1.3.7 in conan, but now example in README fails on Linux with clang 6, 7, 10 & 11 (also with gcc 7), but surprisingly not with clang 8 & 9:

```
/home/conan/.conan/data/cpp-peglib/1.3.7/bincrafters/testing/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/peglib.h:347:10: error: no member named 'from_chars' in namespace 'std'
    std::from_chars(sv.data(), sv.data() + sv.size(), n);
    ~~~~~^
```

I guess it comes from https://github.com/yhirose/cpp-peglib/pull/163

**Comment by yhirose** [comment]
@SpaceIm, thank you for the feedback.
@Apache-HB, do you have any clue?

**Comment by SpaceIm** [comment]
Actually, `if constexp` is not the good tool for this case. Even if the condition is false, the compiler must be able to know what is `std::from_chars`.

**Comment by SpaceIm** [comment]
with this patch, all compilers seem to be happy:

```patch
--- a/peglib.h
+++ b/peglib.h
@@ -13,9 +13,6 @@
 #include <cctype>
 #if __has_include(<charconv>)
 #include <charconv>
-#define CPPPEGLIB_HAS_CHARCONV true
-#else
-#define CPPPEGLIB_HAS_CHARCONV false
 #endif
 #include <cstring>
 #include <functional>
@@ -343,9 +340,13 @@ inline std::string resolve_escape_sequence(const char *s, size_t n) {
 
 template <typename T> T token_to_number_(std::string_view sv) {
   T n = 0;
-  if constexpr (CPPPEGLIB_HAS_CHARCONV && !std::is_floating_point<T>::value) {
+#if __has_include(<charconv>)
+  if constexpr (!std::is_floating_point<T>::value) {
     std::from_chars(sv.data(), sv.data() + sv.size(), n);
   } else {
+#else
+  if constexpr (true) {
+#endif
     auto s = std::string(sv);
     std::istringstream ss(s);
     ss >> n;
```

Maybe not the most elegant, but it works.

**Comment by yhirose** [comment]
@Apache-HB , I am thinking the @SpaceIm's solution looks better. If you don't see any problem, I'll take the solution. Please let me know your thought. Thanks.

**Comment by Apache-HB** [comment]
@yhirose The second proposed change looks like it would be the ideal one to make.

**Comment by yhirose** [comment]
@SpaceIm, @Apache-HB, I applied the second proposal to the master. Could you test it? If it works, I'll release a new version.

**Comment by SpaceIm** [comment]
It's not exactly the second proposal, I'll test it but I think that it will fail for some compilers, because `std::from_chars` is still there (not removed through preprocessing).

**Comment by yhirose** [comment]
@SpaceIm, ok. I probably don't fully understand what you are experiencing... I'll revert ef10e7c. Could you provide a pull request that fixes the problem you mentioned? Please make sure that it now supports C++17 or later. Thanks for your help.

**Comment by SpaceIm** [comment]
Actually, there is just an extra `std::from_chars(sv.data(), sv.data() + sv.size(), n);` after preprocessing macros, I can submit a PR.
