### ISSUE TITLE
Possible bug when using `precedence` with rule names

### ISSUE THREAD

**Issue by Apache-HB** [yhirose/cpp-peglib#169]
with a simple grammar such as 
```
expr    <- ident (binop ident)* {
    precedence
        L * / %
        L + -
}

binop   <- < add / sub / mul / div / mod >

~add    <- '+'
~sub    <- '-'
~mul    <- '*'
~div    <- '/'
~mod    <- '%'

ident   <- < [a-zA-Z_][a-zA-Z0-9_]* > 

%whitespace <- [ \t\r\n]*
```
the expression `a + b * c` is valid.
but when modifying the `expr` rule to use rule names rather than literals
```
expr    <- ident (binop ident)* {
    precedence
        L mul div mod
        L add sub
}
```
The expression `a + b * c` fails to parse due to `unexpected 'b', expected <binop>`
Is this a bug or intended design?

**Comment by yhirose** [comment]
@Apache-HB, it's an intended design. The section only accepts operator *literal* tokens. I'll update README.
