### ISSUE TITLE
PEG Playground treat warning as error

### ISSUE THREAD

**Issue by micrenda** [yhirose/cpp-peglib#170]
I am creating a very complex grammar and [PEG Playground](https://yhirose.github.io/cpp-peglib/) is a wonderful resource.
Unfortunately, in the latest releases, it seems that it treats the warning message "ENTITY is not referenced" as a fatal error making the PEG invalid (however in cpp-peglib it is just a warning).

Can we restore the previous behavior or not to let warning to make the document invalid?

I know that the right number of warning in a project is zero, but during the development of a complex grammar, if would be nice to be able to still use the PEG Playground.

Regards!

**Comment by yhirose** [comment]
@micrenda, thanks for the report! I fixed it. Please make sure the PEG Playground page is properly reloaded before testing.

**Comment by micrenda** [comment]
You made my day :+1: 
Thank you!
