### ISSUE TITLE
PEG Playground: Unicode display in Linux browsers

### ISSUE THREAD

**Issue by kkayal** [yhirose/cpp-peglib#171]
The following issue is only about the [PEG Playground](https://yhirose.github.io/cpp-peglib/) and it seems only for Linux.

When I enter a line with some Unicode in it, the browser shows only the upper half of it. This makes it very hard to read. For example the grammar:

```
start <- 'ぁ'
# comment
```

is displayed in a way that the second line overlaps half of the first line.

This happens with my Ubuntu 20.04.2 LTS. I use firefox and chromium. Same result.

However, I tested the same with safari and firefox on mac (big sur) and see no problem. Also edge and firefox in windows 10 display the same thing just fine.

**Comment by yhirose** [comment]
@kkayal, thanks for the report, but I can't do anything for it, because that's due to the font rendering engine issue on the OS...
