### ISSUE TITLE
[ARM systems regression] very slow parsing and 100% cpu usage

### ISSUE THREAD

**Issue by enricop** [yhirose/cpp-peglib#173]
Hello,
we are using "cpp-peglib" inside the [CANdb](https://github.com/GENIVI/CANdb) project.

Using the "cpp-peglib", at [this commit](https://github.com/yhirose/cpp-peglib/commit/11ed83e) dated Aug 27, 2020, performances are the same on x86 systems and ARM systems.

Instead trying the lastest commit on "cpp11" branch, and trying the latest commit on "master" branch, we have very slow performances on ARM systems.

"cpp11" branch, and latest commit on "master" branch, works fine on x86 systems.

It looks like there is a loop that never exits, or the loop exits only after a long time. Maybe for a difference in compiler output for ARM systems.

More details here: https://github.com/GENIVI/CANdb/issues/39

thanks for your support,
enrico

**Comment by yhirose** [comment]
@enricop, thanks for the report. I just wonder how I can reproduce it. Could you provide a smallest possible example for me? I'll try to run it on my raspberry PI 4 that uses ARM Cortex-A72. Thanks for your help!

**Comment by enricop** [comment]
hello,
this is the grammar we are using: [dbc_grammar.txt](https://github.com/yhirose/cpp-peglib/files/6472687/dbc_grammar.txt)

the original one is here:  https://github.com/GENIVI/CANdb/blob/cpp_peglib_137/src/dbc_grammar.peg

I've sent you an email with the textfile we are parsing.

from the test I made the:
- good commit is [this](https://github.com/yhirose/cpp-peglib/commit/11ed83e) (dated Aug 27, 2020)
- bad commits are: the last "cpp11" branch commit, the last "master" branch commit

thank you.

**Comment by enricop** [comment]
on ARM we are using compiler "arm-fslc-linux-gnueabi-g++" 10.2.0 with compiler specific extensions _disabled_

**Comment by yhirose** [comment]
@enricop, thank you. It seem like https://github.com/yhirose/cpp-peglib/commit/b92da07beddd286cc16ef3620793e297a5f17a6c (#128) causes this performance issue. I'll hopefully find time next week to investigate it. Thanks for your patience. Please let me know if you find any other information regarding it.

**Comment by yhirose** [comment]
@enricop, I measured performance with the grammar and source from you on my Raspberry PI 4.

As you can see below, I don't see any performance difference between `master`, `cpp11` and `v0.1.13`...

```
pi@raspberrypi:~/cpp-peglib/build $ git checkout master
Already on 'master'
Your branch is behind 'origin/master' by 64 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

pi@raspberrypi:~/cpp-peglib/build $ make peglint && time ./lint/peglint dbc_grammar.txt CAN2.dbc 
[100%] Built target peglint

real	0m8.210s
user	0m8.200s
sys	0m0.010s

pi@raspberrypi:~/cpp-peglib/build $ git checkout cpp11
Switched to branch 'cpp11'
Your branch is up to date with 'origin/cpp11'.

pi@raspberrypi:~/cpp-peglib/build $ make peglint && time ./lint/peglint dbc_grammar.txt CAN2.dbc 
Scanning dependencies of target peglint
[ 50%] Building CXX object lint/CMakeFiles/peglint.dir/peglint.cc.o
[100%] Linking CXX executable peglint
[100%] Built target peglint

real	0m8.173s
user	0m8.173s
sys	0m0.000s

pi@raspberrypi:~/cpp-peglib/build $ git checkout -b v0.1.13 refs/tags/v0.1.13 
Switched to a new branch 'v0.1.13'

pi@raspberrypi:~/cpp-peglib/build $ make peglint && time ./lint/peglint dbc_grammar.txt CAN2.dbc 
Scanning dependencies of target peglint
[ 50%] Building CXX object lint/CMakeFiles/peglint.dir/peglint.cc.o
[100%] Linking CXX executable peglint
[100%] Built target peglint

real	0m8.224s
user	0m8.224s
sys	0m0.000s
```

Am I missing something in order to reproduce the performance problem?
Any further information is welcome.

**Comment by enricop** [comment]
hello, 
thank you for these test.
I'll try again on next Monday running the "peglint" on our ARM A15 and I'll let you know.

**Comment by enricop** [comment]
Hello,
I've tested on ARM A15 the two version below:

CANdb with **v0.1.13** peglib the loading times are:
CAN1.dbc loaded in = 1079[ms]
CAN2.dbc loaded in = 1920[ms]

CANdb with **master** peglib the loading times are:
CAN1.dbc loaded in = 1216[ms]
CAN2.dbc loaded in = 2124[ms]

so it looks like the are no regressions on ARM A15.
The system where I had the issue was an ARM A9 (imx6-quad), but we no longer use it.
