### ISSUE TITLE
Peg grammar for APL

### ISSUE THREAD

**Issue by AbdurRaafay** [yhirose/cpp-peglib#179]
I am trying to write peg grammar for APL. How do i write the grammar for the vector addition
2 + 3 4 5 6 7 
where 3 4 5 6 7 is the numeric vector.  Here two vectors are being added

2 34 56 67 92 + 3 4 5 6 7

I have looked  the APL grammar in rust's pest peg grammar library 

https://github.com/pest-parser/book/blob/master/examples/jlang-parser/src/j.pest

program = _{ SOI ~ "\n"* ~ (stmt ~ "\n"+) * ~ stmt? ~ EOI }

stmt = _{ expr }

expr = {
      assgmtExpr
    | monadicExpr
    | dyadicExpr
    | string
    | terms
}

monadicExpr = { verb ~ expr }

dyadicExpr = { (monadicExpr | terms) ~ verb ~ expr }

assgmtExpr = { ident ~ "=:" ~ expr }

terms = { term+ }

term = _{ decimal | integer | ident | "(" ~ expr ~ ")" }

verb = {
    ">:" | "*:" | "-"  | "%" | "#" | ">."
  | "+"  | "*"  | "<"  | "=" | "^" | "|"
  | ">"  | "$"
}

integer = @{ "_"? ~ ASCII_DIGIT+ }

decimal = @{ "_"? ~ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT* }

ident = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }

string = @{ "'" ~ ( "''" | (!"'" ~ ANY) )* ~ "'" }

WHITESPACE = _{ " " | "\t" }

COMMENT = _{ "NB." ~ (!"\n" ~ ANY)* }

where ~ means "followed by" .  Below is a quotation from the online pest book

"Notice how we use pest's @ modifier to make each of these rules atomic, meaning implicit whitespace is forbidden, and that interior rules (i.e., ASCII_ALPHA in ident) become silent — when our parser receives any of these tokens, they will be terminal:"

How do you translate the pest grammar above in cpp-peglib

**Comment by yhirose** [comment]
@AbdurRaafay, thanks for the feedback. Since I am not familiar with rust's pest peg grammar at all, I can't give you a meaningful help. `@{ ... }` looks like cpp-peglib's token operator `< ... >`.
