### ISSUE TITLE
std::to_chars is not available on macOS 10.14 and earlier despite charconv header existing

### ISSUE THREAD

**Issue by trilader** [yhirose/cpp-peglib#181]
This is related to #167 

When building on macOS 10.15 and newer but deploying to an earlier macOS version (10.14 and below) `<charconv>` exists but `std::from_chars` is not actually defined.

As per [this libc++ change](https://reviews.llvm.org/D74626) the necessary symbols to actually use `std::from_chars` were only introduced in macOS 10.15.

My current (ugly) workaround is to add `&& (!defined(__APPLE__) || MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_15)` to the `__has_include(<charconv>)` check.

**Comment by yhirose** [comment]
@trilader, thanks for the feedback. I think it's not a matter of version of macOS, but XCode version or clang version. Could you investigate it more please, and send a pull request? Thanks!

**Comment by trilader** [comment]
Hm: I unfortunately can't reproduce this anymore. It was happening consistently but doesn't anymore after trying a bunch of things and then reverting my project repository to the state I had the error with... I have no idea what I did to get it working.
Clean/Rebuild didn't help before but maybe there was something cached elsewhere outside my project and build directories.
