### ISSUE TITLE
grammar mistake in the github home page

### ISSUE THREAD

**Issue by asmwarrior** [yhirose/cpp-peglib#182]
In the home page of the github, I see this:

~~~~
peg::parser parser(R"(
  ROOT  <-  _ ITEM (',' _ ITEM _)*
  ITEM  <-  ([a-z])+
  ~_    <-  [ \t]*
)");

parser["ROOT"] = [&](const SemanticValues& vs) {
  assert(vs.size() == 2); // should be 2 instead of 5.
};

auto ret = parser.parse(" item1, item2 ");
~~~~

Please note that ` ([a-z])+` should be replaced by ` ([a-z0-9])+`, otherwise, the test string `" item1, item2 "` will get failed to parse.

**Comment by yhirose** [comment]
@asmwarrior, oops... You are completely right! I'll fix it.

**Comment by asmwarrior** [comment]
Hi, there is still one issue in the next sample grammar after your fixed grammar.

~~~~
peg::parser parser(R"(
  ROOT  <-  ~_ ITEM (',' ~_ ITEM ~_)*
  ITEM  <-  ([a-z])+
  _     <-  [ \t]*
)");
~~~~

This should also be fixed.

**Comment by yhirose** [comment]
Thanks!
