### ISSUE TITLE
What does the word expression mean and used for?

### ISSUE THREAD

**Issue by asmwarrior** [yhirose/cpp-peglib#183]
~~~~
peg::parser parser(R"(
  ROOT         <-  'hello' 'world'
  %whitespace  <-  [ \t\r\n]*
  %word        <-  [a-z]+
)");

parser.parse("hello world"); // OK
parser.parse("helloworld");  // NG
~~~~

This is a question about the `%word` usage, what does this expression try to solve, I mean if I don't use `%word`, what is the problem I will have?

`%word        <-  [a-z]+`, when defined this, the root rule `ROOT         <-  'hello' 'world'` will have different meanings?

Thanks.

**Comment by yhirose** [comment]
`%word` should be used with `%whitespace`. It's needed when two or more keywords appear continuously such as "else if". It's like `RULE <- 'else' !%word %whiltespace 'if'`. Hope it helps.

**Comment by asmwarrior** [comment]
Thanks, you mean when `%word` rule is used, the space between the two literals will automatically get skipped?

I did a simple test:

Grammar:
~~~~
ROOT         <-  WORD %whitespace WORD
%whitespace  <-  [ \t\r\n]*
WORD         <-  [a-z]+
~~~~
This can correctly parse `hello world`.

While, if I remove the `%whitespace` from the `ROOT` rule, like this:

~~~~
ROOT         <-  WORD  WORD
%whitespace  <-  [ \t\r\n]*
WORD         <-  [a-z]+
~~~~

Then, parsing `hello world` just failed with such error message `1:6 syntax error, unexpected ' ', expecting <WORD>.`, this means the space after the `hello` is not skipped? But I see that the `%whitespace` means the spaces will be automatically skipped?

This is not still clear for me, can you help? Thanks.

**Comment by asmwarrior** [comment]
OK, maybe I have some findings:

~~~~
ROOT         <-  WORD WORD
%whitespace  <-  [ \t\r\n]*
WORD         <-  <[a-z]+>
~~~~

If I change the grammar to this, the WORD rule has token boundary operator, so the white space will be skipped between WORD in the first ROOT rule.

This sounds like:
~~~~
WORD         <-  <[a-z]+>
~~~~
sounds like:
~~~~
%word         <-  <[a-z]+>
~~~~

But `%word` doesn't have a rule name?

**Comment by yhirose** [comment]
Sorry that I probably don't fully understand what you are trying to do... Anyway, the intention of `%word` is to provide a way of preventing undesirable concatenation of keywords automatically in common situations. (like only accept 'else if', but report 'elseif' as an error.) It can only work when `%whiltespace` is used.
