### ISSUE TITLE
How playground native.wasm is built ?

### ISSUE THREAD

**Issue by mingodad** [yhirose/cpp-peglib#185]
I've been looking through this repository and your projects but couldn't find any mention for how `native.wasm` or the `playground` is built, could you share it ?

**Comment by yhirose** [comment]
This is it!
https://github.com/yhirose/cpp-peglib/blob/4d67d96d7ace0830549908a6fae9064d74683f5a/docs/build.sh#L1-L2

**Comment by mingodad** [comment]
Thank you !
It was in front of my nose all the time but somehow I missed it !
