### ISSUE TITLE
Could you please predicate tests, lint, examples on cmake options?

### ISSUE THREAD

**Issue by yurivict** [yhirose/cpp-peglib#188]
[Here](https://github.com/yhirose/cpp-peglib/blob/master/CMakeLists.txt#L20) and in subsequent lines.

The package builder doesn't need tests, lint, examples, and these lines have to be patched out.
It would be a lot nicer if they were conditional on dedicated cmake variables, ex. ```CPP_PEGLIB_TESTS```, etc.

Thank you,
Yuri

**Comment by yhirose** [comment]
Sorry, but I am not interested in adding these options. This is just a small library for my personal projects. :)
