### ISSUE TITLE
Implementing INDENT/DEDENT tokens and incremental parsing

### ISSUE THREAD

**Issue by gavrilikhin-d** [yhirose/cpp-peglib#190]
Is it possible to create REPL for python-like language with your parser? 

How do you handle INDENT and DEDENT tokens or resume parsing after new line received in REPL?

**Comment by yhirose** [comment]
Honestly, I don't know because I have never tried to implement such indent based language with cpp-peglib.
It could be helpful for you: https://stackoverflow.com/questions/11659095/parse-indentation-level-with-peg-js

**Comment by fruffy** [comment]
> Honestly, I don't know because I have never tried to implement such indent based language with cpp-peglib. It could be helpful for you: https://stackoverflow.com/questions/11659095/parse-indentation-level-with-peg-js

Do you think there is a way to implement this with peglib? Basically keeping track of indent levels for a particular rule and having a way to increment and decrement this level.

**Comment by mingodad** [comment]
The Codon project have a cpp-peglib fork https://github.com/exaloop/cpp-peglib and it has INDENT/DEDENT implemented there.
