### ISSUE TITLE
Error parsing valid charset class

### ISSUE THREAD

**Issue by mingodad** [yhirose/cpp-peglib#195]
Trying to parse a valid `peg` grammar with `cpp-peglib` I found that it doesn't accept the charset class shown bellow:
```
plusorless  <-  [+-]
```
Playgound output:
```
1:21 syntax error
```
Changing `Range` to the one shown bellow fix the issue:
```
Range <-  (Char  '-'  ! ']' Char) /  Char
```
Hardcoded fix in `peglib.h`:
```
g["Range"] <= cho(seq(g["Char"], chr('-'), npd(chr(']')), g["Char"]), g["Char"]);
```

**Comment by yhirose** [comment]
@mingodad, thank you for the feedback. I tried to make the cpp-httplib PEG parser syntax as faithful as the one described on the 2nd page in [the original Bryan Ford paper](https://bford.info/pub/lang/peg.pdf), but the enhancement that you suggests looks reasonable. I'll consider to take the suggestion. Thank you.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/357397/166462465-a748389a-c542-4dba-bc79-c7c6d12a65e8.png">

**Comment by mingodad** [comment]
Another missing feature are some escape sequences like `\v`, `\f`, ...
```
Char		<- '\\' [abefnrtv'"[\]\\^]
```

**Comment by yhirose** [comment]
`\v`, `\f` are same as #87.
