### ISSUE TITLE
Dictionary bug ?

### ISSUE THREAD

**Issue by mingodad** [yhirose/cpp-peglib#209]
I'm trying to use the `Dicitionary` functionality but it doesn't seem to work properly, I mean **only matching whole words**.

Grammar:
```
START <- 'This is ' anyword ' ' MONTH '.'
MONTH <- 'Jan' | 'January' | 'Feb' | 'February' | '...'
anyword <- !MONTH [a-zA-z]+
```
Input ok:
```
This is when Jan.
```
Input not ok but I expected to be ok:
```
This is Febuo Jan.
```
Output error:
```
1:9 syntax error, unexpected 'Febuo', expecting <anyword>.
```

**Comment by yhirose** [comment]
Here is the correct grammer.

```
START <- 'This is ' anyword ' ' MONTH '.'
MONTH <- ('Jan' | 'January' | 'Feb' | 'February' | '...') ![a-zA-Z]
anyword <- !MONTH [a-zA-z]+
```

**Comment by mingodad** [comment]
Could you add that to the README ?

**Comment by yhirose** [comment]
This is not a problem of Dictionary in particular, since it happens with any literal rules...

<img width="472" alt="image" src="https://user-images.githubusercontent.com/357397/172009069-79853dbb-0123-49f2-8912-5f6ffef937a2.png">

**Comment by mingodad** [comment]
Thank you !
But I still think that having an example with `![a-zA-Z]` or `!IdChar` on the README would help newcomers and probably less issues will be opened by then (like me).

**Comment by yhirose** [comment]
Yes, the current README is like a feature reference document... I agree that it would be very helpful for new users to have something like a practical user guild.

**Comment by mingodad** [comment]
Probably on the playground, a dropdown of examples with inputs, that can grow as new issues/questions arise.
Like here https://go.dev/play/
