### ISSUE TITLE
Syntax parsing fails with MSVC but not with GCC

### ISSUE THREAD

**Issue by Hyvok** [yhirose/cpp-peglib#22]
Hey! I am having a problem where a simple syntax fails to parse with MSVC compiler but seems to work with GCC. Compiling the following code with MSVC (x64) versions 19.00.24213.1 and 18.00.31101 will result in parsing error ie. !parser == true. C++14 support is enabled. If 'in?' is removed from op_cmd token then it starts working again. This works with GCC 5.3.0.  I used the latest cpp-peglib commit 5e67fcb329464396a92c6a561a4ffa7025761a2c. Any ideas what could be going wrong or how I could debug it further?

~~~~
#include <peglib.h>
#include <boost/log/trivial.hpp>

int main()
{
    const auto testSyntax =
    R"(
        main <- op_cmd

        # Set interpolation mode
        intpol_lin      <- 'G01'
        intpol_cw       <- 'G02'
        intpol_ccw      <- 'G03'
        in              <- intpol_lin / intpol_cw / intpol_ccw

        # Operations
        move_intpol     <- 'D01'
        move            <- 'D02'
        flash           <- 'D03'
        sel             <- [XYIJ]
        # If 'in?' then it doesn't crash with VS2015
        op_cmd          <- in? (sel coord)+ (move_intpol / move / flash) '*'

        # General token identifiers
        digit           <- [0-9]
        coord           <- ('+' / '-')? digit+
    )";
    parser parser(testSyntax);

    if(!parser)
    {
        BOOST_LOG_TRIVIAL(error) << "Parser syntax error!";
    }
}
~~~~

**Comment by Hyvok** [comment]
Found out that if I put '(in)?' it works with MSVC as well.

**Comment by yhirose** [comment]
@Hyvok, thank you for the bug report and the workaround!
I am able to reproduce the bug with my latest  Visual C++.
I'll work on the bug as soon as possible, so that you don't have to put extra parenthesis.

**Comment by yhirose** [comment]
@Hyvok, I have just updated `peglib.h`. It should fix the problem.
Please let me know if you still have the problem with the latest version.
Thank you!
