### ISSUE TITLE
Is WeakHolder necessary?

### ISSUE THREAD

**Issue by NotAPenguin0** [yhirose/cpp-peglib#224]
I've been doing some optimization rounds on my own program using cpp-peglib, and found out that parsing is by far the most expensive operation (although this is not surprising). What did surprise me is that the most time consuming part of the parsing is the following line https://github.com/yhirose/cpp-peglib/blob/924588bb6985416413db34c9ba9ddc4709b79f5c/peglib.h#L1465

Since I was curious I changed `weak_` to a be a `std::shared_ptr` and removed all `lock()` calls, which resulted in a near 2x speedup for parsing all my test cases. What I'm wondering is, is this usage of `std::weak_ptr` necessary or can it be avoided some other way? 

Performance stats gathered on Windows 10 (clang-cl), Ryzen 5 3600.

**Comment by NotAPenguin0** [comment]
As a side note, this change doesn't seem to break any of the tests that weren't already broken (see #225 for that). I unfortunately don't have access to a memory leak detector so I can't check for that.

**Comment by yhirose** [comment]
@NotAPenguin0, thanks for the feedback. WeakHolder is necessary to handle a recursive grammar properly (or 'cyclic dependency') as below.

```
S <- A
B <- C A
```

https://stackoverflow.com/questions/27085782/how-to-break-shared-ptr-cyclic-reference-using-weak-ptr

Hope it helps!
