### ISSUE TITLE
feature request: prevent token identity decent

### ISSUE THREAD

**Issue by kfsone** [yhirose/cpp-peglib#236]
```
p <- identifier

NAME_START <- [A-Za-z_]
NAME_CONTINUATION<- NAME_START / [0-9]

identifier <- < NAME_START NAME_CONTINUATION* >
```

given an invalid identifier, this does _not_ report 'expected identifier' but instead exposes the internal terminal name NAME_START:

![image](https://user-images.githubusercontent.com/323009/181384050-4d9a2604-97d2-495b-aca2-bad9a38b2662.png)

perhaps support for

`identifier <- <= NAME_START NAME_CONTINUATION* =>`

could be added to peglib to allow `identifier` to behave in reporting as though it was not a compound?

Bonus points if it could be used to produce:

```
syntax error, unexpected '2', expecting <identifier> could not match <NAME_START>
```

or if I used better labels:

```
program <- identifier
identifier <- <= AllowedIdentifierFirstCharacters AllowedIdentifierCharacters* =>
AllowedIdentifierFirstCharacters <- [A-Za-z_]
AllowedIdentifierCharacters <- AllowedIdentifierFirstCharacters / [0-9]
```
->
```
syntax error, unexpected '2', expecting <identifier>: could not match <AllowedIdentifierFirstCharacters>
```

**Comment by yhirose** [comment]
@kfsone, thanks for the report. I fixed this problem without introducing any new operator.
