### ISSUE TITLE
Crash when there is a Cut operator which doesn't belong to a PrioritizedChoice operator

### ISSUE THREAD

**Issue by kfsone** [yhirose/cpp-peglib#237]
The following grammar causes the playground to lock into an infinite loop:

```
p <- (a E)*
~E <- '\n' / !.
a <- 'x' '=' ↑ t   # << removing the cut solves the problem
t <- 'a' | 'b'
```

**Comment by yhirose** [comment]
@kfsone, thanks for the report, but I can't reproduce it on the playground.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/357397/181420376-20aedb87-ecd6-475d-87ed-04e2f77dac24.png">

Also I am not able to reproduce it with peglint either.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/357397/181420588-2e107ac8-8801-43c2-98ea-3fe3926118b7.png">

**Comment by kfsone** [comment]
Ah, sorry, try the input:
```
x=c
```

![infinite-loop](https://user-images.githubusercontent.com/323009/181451880-35c4f016-9cee-4029-94ce-c100bf1c0666.gif)

**Comment by yhirose** [comment]
Thanks. I am now reproduce it.

**Comment by yhirose** [comment]
This is actually not a infinite loop problem.  This is caused by a Cut operator which doesn't belong to a PrioritizedChoice operator. I changed the title.
