### ISSUE TITLE
%t doesn't (always) show the unexpected token

### ISSUE THREAD

**Issue by kfsone** [yhirose/cpp-peglib#238]
Given:
```
program <- enum+

# treat any non-punctuated sequence of alpha/digits/underscores as a word,
%word <- [a-zA-Z0-9_]+

~space <- [ \r\t\n]

enum <- ~enum_keyword space+ enum_kind

enum_keyword <- "enum"

## VARIANT 1:
#enum_kind <- ( sequence / bitmask / %recover(untyped_enum) )
#sequence <- "sequence"
#bitmask <- "bitmask"

## VARIANT 2:
#enum_kind <- ( "sequence" / "bitmask" / %recover(untyped_enum) )


untyped_enum <- '' { message "invalid/missing enum type, expected one of 'sequence' or 'bitmask', got '%t'"}
```

the input `enum sequencer` does not report `got 'sequencer'`, instead it reports `got 'sequence'`.

![image](https://user-images.githubusercontent.com/323009/181388649-c940b4e1-5672-427b-ace2-1fd4b1231bd6.png)

![image](https://user-images.githubusercontent.com/323009/181388632-2ab5dc52-fb6d-4eda-ac30-66b98c50ab9a.png)

edit: maybe this is a size constraint issue? if I gave it a string shorter than the first/longest candidate:

![image](https://user-images.githubusercontent.com/323009/181388675-ce01ef6f-dd65-494a-aa4d-e9731f7cfee0.png)

or this oddity (the input is 'bitmaskerror' but %t prints 'bitmaske')

![image](https://user-images.githubusercontent.com/323009/181388838-9d3b30d8-4bf7-44ef-95a5-e2ea4727cb6e.png)

edit: yes, this appears to be the problem:

![image](https://user-images.githubusercontent.com/323009/181388879-bd0acd76-72dc-43a9-b54c-d3e272f62c99.png)

**Comment by yhirose** [comment]
Thanks for the report!
