### ISSUE TITLE
"\w" and "\d" character class shortcuts

### ISSUE THREAD

**Issue by kfsone** [yhirose/cpp-peglib#249]
Would it be possible to add the regex escapes '\w' and '\d' to the character sequences, and optionally their inverses?

\w <- [a-zA-Z0-9_]
\W <- ![a-zA-Z0-9_]
\d <- [0-9]
\D <- ![0-9]

https://stackoverflow.com/questions/1576789/in-regex-what-does-w-mean

**Comment by yhirose** [comment]
Good suggestion!

**Comment by Andos** [comment]
This would be a really nice feature.

There is also the unicode classes to consider:
`\p{L}`  Any unicode letter
`\p{Z}` Any kind of whitespace or invisible separator. 
`\p{N}` Any kind of numeric character in any script. 
`\p{P}` Any kind of punctuation character. 

See more here:
https://www.regular-expressions.info/unicode.html#category

**Comment by yhirose** [comment]
Merged to #87.
