### ISSUE TITLE
Optional suffix with no %whitespace

### ISSUE THREAD

**Issue by kfsone** [yhirose/cpp-peglib#250]
Trying to capture command-line arguments as "switch and value" without allowing whitespace between the two parts.

The following grammar "works", but unfortunately allows spaces between CMDSWITCH and CMDVALUE.

```
Grammar
	<-	( _ / Statement )* EOI


Statement
    <-  Default

Default
	<-	Asset ↑ CmdlineArg+ ↑ Newline+
Asset
    <-  < NAME >

CmdlineArg
	<-	CMDSWITCH ( '=' (STRING / CMDVALUE)? )?

~Newline
	<- < COMMENT? [\r\n]+ >


%whitespace
	<- [ \t]*

%word
	<- [a-zA-Z][a-zA-Z0-9_.-]*

~_
	<- (COMMENT? EOL)+

~EOL
    <- '\r'? '\n'

~EOI
    <- ! .      # literally: not anything

~COMMENT
    <- < '//' [^\n]* >

NAME
	<- < [a-zA-Z_] [a-zA-Z0-9_]* >

STRING
    <- < '"' ( '\\' !('\r'? '\n') / '""' / [^"\\\r\n] )* '"' >

CMDSWITCH
	<- < '-' '-'? [a-zA-Z0-9_] [a-zA-Z0-9_.-]* >

CMDVALUE
    <- < ( '\\' [^\r\n] / [^ \t\r\n\\] )+ >
```

![image](https://user-images.githubusercontent.com/323009/194986361-366f6394-474e-4582-9931-5f368583baae.png)

Using '<' ... '>' in CmdArg results in it only producing a single value, however

![image](https://user-images.githubusercontent.com/323009/194986478-e41e9790-6d41-4596-9950-365df848a51d.png)

Is there some way to both prevent whitespace AND still retain the split values?

**Comment by yhirose** [comment]
Could you make the grammar as small as possible, so that I can understand what you are mentioning? Thanks!

**Comment by kfsone** [comment]
```
Grammar <- ( NAME CmdlineArg EOL )* EOI


%whitespace <- [ \t]*
%word <- [a-zA-Z][a-zA-Z0-9_.-]*
~EOL <- ('\r'? '\n')+
~EOI <- ! .


CmdlineArg <- CMDSWITCH ( '=' (STRING / CMDVALUE)? )?

NAME <- < [a-zA-Z_] [a-zA-Z0-9_]* >

STRING <- < '"' ( '\\' !('\r'? '\n') / '""' / [^"\\\r\n] )* '"' >

CMDSWITCH <- < '-' '-'? [a-zA-Z0-9_] [a-zA-Z0-9_.-]* >

CMDVALUE <- < ( '\\' [^\r\n] / [^ \t\r\n\\] )+ >
```

inputs, correct:

```
thing1 --switch
thing2 --switch=value
```

but it also incorrectly allows

```
thing3 --switch = something
```

And, demonstration that it currently parses the last, incorrectly:

![image](https://user-images.githubusercontent.com/323009/197086559-2208e5e2-09ea-4123-9818-a78d473830c3.png)

**Comment by kfsone** [comment]
One work around is to write a token.immediate to do this match, but because it can't use named patterns/named terminals, it results in duplication of grammar segments, and I really don't want to embed the string pattern multiple times :)

**Comment by yhirose** [comment]
As long as you use `%whitespace`, there is no way to disallow spaces between tokens. Sorry...
