### ISSUE TITLE
`BUILD_TESTS` vs. `PEGLIB_BUILD_TESTS`

### ISSUE THREAD

**Issue by russkel** [yhirose/cpp-peglib#251]
Hello,

Is there a reason to use this over the standard `BUILD_TESTS`? Other tooling will have to handle this case explicitly.

https://github.com/yhirose/cpp-peglib/blob/dde4aaeb2fd7043f1548cee7e4f1bffdd2001a53/CMakeLists.txt#L13

**Comment by yhirose** [comment]
@NotAPenguin0, could you explain it to @russkel since it came from your contribution. Thanks!

**Comment by yhirose** [comment]
@russkel, can I simply rename `PEGLIB_BUILD_TESTS` to `BUILD_TESTS`? If so, I'll do it right away. :)

**Comment by russkel** [comment]
Yep that'll do it :).

**Comment by yhirose** [comment]
Thanks!

**Comment by russkel** [comment]
Thanks for fixing this @yhirose !
