### ISSUE TITLE
vs.choice() always returns 0 when %whitespace is defined.

### ISSUE THREAD

**Issue by CameronTofer** [yhirose/cpp-peglib#266]
Hi, if I define %whitespace then prioritized choices always return 0.  

auto grammar = R"(
type    <- 'string' / 'int' / 'double'
%whitespace     <-  [ \t\r\n]*
)"

...

parser["type"] = [](const SemanticValues& vs) { 
        return vs.choice();  // choice and choice count are always 0.  works if %whitespace line is deleted
};

am I missing something?

**Comment by yhirose** [comment]
@CameronTofer thanks for the report. It looks a bug. I'll look into it when I have time. Thanks!
