### ISSUE TITLE
[Question] How to get line/column information in a semantic action?

### ISSUE THREAD

**Issue by maychan111** [yhirose/cpp-peglib#27]
When parsing some grammar, I would like to keep parsing and only record minor semantics issues as warnings at the end, along with the line/column number with the warnings.  Therefore, it would be nice to have the line/col information during an semantic action. 

However, the only way I can see to get at the line/column information is to actually throw the parse_error exception and let the log function to be called.  

Any suggestions?

**Comment by yhirose** [comment]
@maychan111, sorry for the late reply. I just found this message...

`enable_ast()` method in peglib.h may do the similar that you want to do.

```c++
    template <typename T = Ast>
    parser& enable_ast() {
        for (auto& x: *grammar_) {
            const auto& name = x.first;
            auto& rule = x.second;

            if (!rule.action) {
                auto is_token = rule.is_token;
                rule.action = [=](const SemanticValues& sv) {
                    auto line = line_info(sv.ss, sv.c_str()); // <- Translate the current text position into line and columns numbers.
```

`SemanticValue` structure has `ss` member which is the start pointer of the input source. `sv.c_str()` gives us the start pointer to the matched string for the rule. `line_info` call with those pointers will find line and column numbers for the position. (As you see in the code, `line_info` uses a naive linear algorithm. So I recommend to call this function only when it's necessary. )

Is this information enough for you to solve your problem? (If so, I'll update the README regarding this issue.)

Thanks for the report!

**Comment by maychan111** [comment]
Great suggestion.  It totally works!
