### ISSUE TITLE
Providing a base class to AstBase throws exception.

### ISSUE THREAD

**Issue by gamagan** [yhirose/cpp-peglib#271]
Checkout [#d9dfc5b] of 2023.3.15 (latest, as of this post)

The following works:

```cpp
using SharedAst = std::shared_ptr<peg::AstBase<peg::EmptyType>>; // peg::Ast
SharedAst ast;
parser.parse(code, ast);
```

The following throws a std:bad_any_cast.
```cpp
struct AstDecor {
    bool mFoobar = false;
};
using SharedAst = std::shared_ptr<peg::AstBase<AstDecor>>;
SharedAst ast;
parser.parse(code, ast);
```

The error is thrown at this location:
![image](https://user-images.githubusercontent.com/9970152/227690369-4dfa82e1-823d-4af2-a2c3-302b28df07d7.png)

**Comment by yhirose** [comment]
@gamagan thanks for the feedback. Here is a workable example. Hope it helps!

https://github.com/yhirose/cpp-peglib/blob/17e069fbc5630300dfcdd017846662b77fb65ae8/test/test1.cc#L403-L418
