### ISSUE TITLE
Throw from action gets confusing error

### ISSUE THREAD

**Issue by diyessi** [yhirose/cpp-peglib#273]
If an action throws, for example because an `any_cast` has the wrong type, the problem typically (for me, at least) shows up in the `~Context` at `assert(cut_stack.empty());`, which can be very confusing until you realize what is really going on.

**Comment by curldivergence** [comment]
Btw the same problem was mentioned in #269, for now I’ve just commented out that assertion from  `cpp-peglib`.

**Comment by yhirose** [comment]
@diyessi, @curldivergence could you try the latest peglib.h? Hope it fixes the issue.
