### ISSUE TITLE
[Question] Multiline object with matched deliminators

### ISSUE THREAD

**Issue by LordAro** [yhirose/cpp-peglib#277]
I'm trying to construct a grammar that matches the following:
```
OBJECT : flibble
=====
foobar
=====
```

Where "foobar" is a multiline string containing anything, deliminated by an arbitrary (but matching) number of equals symbols.

This is the best I've come up with, but this requires putting `< >` around the entire string, so the AST ends up containing the deliminators as well as the string body. If I remove the `<>` from `MULTILINE_STRING`, it doesn't match anymore.

```
OBJECT <- 'OBJECT' COLON ALPHANUM MULTILINE_STRING
ALPHANUM <- < [A-Za-z][A-Za-z0-9]* >
MULTILINE_STRING <- < $eq<EQ+> MULTILINE_STRING_DATA $eq >
MULTILINE_STRING_DATA <- < (!$eq .)* >
EQ <- '='
COLON <- ':'
%whitespace <- [ \t\r\n]*
```

Is there something better I can do?

**Comment by mingodad** [comment]
Playing on the playground I came with this:
```
OBJECT <- 'OBJECT' COLON ALPHANUM MULTILINE_STRING_HEAD MULTILINE_STRING
ALPHANUM <- < [A-Za-z][A-Za-z0-9]* >
~MULTILINE_STRING_HEAD <- < $eq<EQ+> >
MULTILINE_STRING <- <MULTILINE_STRING_DATA> $eq 
MULTILINE_STRING_DATA <- (!$eq .)* 
EQ <- '='
COLON <- ':'
%whitespace <- [ \t\r\n]*
```
Output:
```
+ OBJECT
  - COLON (:)
  - ALPHANUM (flibble)
  - MULTILINE_STRING (foobar
)
```
