### ISSUE TITLE
in your calculator sample, how to support  negative numbers? 

### ISSUE THREAD

**Issue by haskellstudio** [yhirose/cpp-peglib#28]
for example :  -2 + 3

**Comment by mjsurette** [comment]
If you check out pl0.peg in the grammar folder the expression definition has signed numbers.

HTH

Mike

**Comment by yhirose** [comment]
@haskellstudio, hope @mjsurette's comment helps you.
https://github.com/yhirose/cpp-peglib/blob/master/pl0/pl0.cc#L49
