### ISSUE TITLE
Performance comparison with boost::spirit, PEGTL etc.?

### ISSUE THREAD

**Issue by zengmao** [yhirose/cpp-peglib#282]
The grammar definition syntax of cpp-peglib seems more pleasant than alternatives like boost::spirit and PEGTL, since a plain text format is used instead of a DSL based on operator overloading or templates. However, does this come with any performance cost? For newcomers like me exploring options, some comparisons will be helpful.

**Comment by mingodad** [comment]
Go ahead produce the comparisons and show it here !

**Comment by yhirose** [comment]
@zengmao thanks for the question. As for making a parser, boost::spirit and PEGTL are faster, since they do it on compile time while cpp-peglib does it on runtime. As for performance of a generated parser, I am not sure because I have never tried those libraries...
