### ISSUE TITLE
build errors with clang++ in debug mode

### ISSUE THREAD

**Issue by mjsurette** [yhirose/cpp-peglib#29]
As the subject line indicates I have build problems with clang 5.0.0 in debug mode.

`[ 18%] Linking CXX executable test-main
CMakeFiles/test-main.dir/test.cc.o:(.debug_info+0x84b85): undefined reference to `peg::enabler'
CMakeFiles/test-main.dir/test.cc.o:(.debug_info+0x84bbf): undefined reference to `peg::enabler'
CMakeFiles/test-main.dir/test.cc.o:(.debug_info+0x84bed): undefined reference to `peg::enabler'
CMakeFiles/test-main.dir/test.cc.o:(.debug_info+0x84c1b): undefined reference to `peg::enabler'
CMakeFiles/test-main.dir/test.cc.o:(.debug_info+0x84c49): undefined reference to `peg::enabler'
CMakeFiles/test-main.dir/test.cc.o:(.debug_info+0x84c77): more undefined references to `peg::enabler' follow
clang-5.0.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/CMakeFiles/test-main.dir/build.make:95: test/test-main] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: test/CMakeFiles/test-main.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
`

It works in release mode and gcc works in both modes.

Awesome library btw.  I especially like being able to use parser combinators.  I really shoots up the performance.

Mike

**Comment by yhirose** [comment]
@mjsurette, thanks for the build error report with clang 5.0.0. I'll take a look at it when I have time.

BTW, when it comes to the parser combinators, the PEG grammar parser itself is written with combinators.
https://github.com/yhirose/cpp-peglib/blob/master/peglib.h#L1770-L1835

**Comment by yhirose** [comment]
@mjsurette, I fixed it. Could you test with the latest peglib.h?
It seems like clang++ 5.0.0 on release doesn't handle C++ SFINAE very well...
