### ISSUE TITLE
Expose a choice field for SemanticValues in dictionaries

### ISSUE THREAD

**Issue by joankaradimov** [yhirose/cpp-peglib#291]
I notice that the [Trie](https://github.com/yhirose/cpp-peglib/blob/6201458f3b685ddc93d1729893e292ded7c9c609/peglib.h#L378) behaves more like a set and its `match` method returns the match length. Would it be viable to make it behave like a map with its `match` returning the choice index (that can be kept as an additional field in the `Info` struct).

I think that would make for a more consistent interface. And allow for more performant grammar handling in certain cases.

**Comment by yhirose** [comment]
Sounds good.
