### ISSUE TITLE
Whitespace rule can spoil error messages

### ISSUE THREAD

**Issue by kfsone** [yhirose/cpp-peglib#292]
I've been trying to improve the quality of errors reported by some of my earlier peglib grammars, but when I simplified the grammars the error messaging changed, eventually I realized that peglib is currently somewhat variable about what it selects to report as expecting.

```
File <- Compound
Value <- [0-9]+
Field <- [a-z]+

### VVVVV changes here VVVVV ###
%whitespace <- [ \t\r\n]*
#%whitespace <- SPACE*
#~SPACE <- [ \t\r\n]

Compound <- Unit / Array / Object
#Compound <- Array / Object
### ^^^^^ changes here ^^^^^ ###

Unit <- '{' '}'
Array <- '{' Object+ '}'
Object <- '{' ObjectMember+ '}'
ObjectMember <- Field '=' Value ','?
```
given the input `{{1}}` or `{{a=1,2}}` I get various different errors depending on what is commented in/out

Closest to what I expect:
![image](https://github.com/yhirose/cpp-peglib/assets/323009/df57c7f4-dbb7-4f55-b105-ebac99188403)

But if I use a production in whitespace (which I do for comments), suddenly it tells the user it was expecting a space:
![image](https://github.com/yhirose/cpp-peglib/assets/323009/56b2997b-1086-45fd-a902-f2ca4d968185)

Simple whitespace again but without unit, it now gives me an accurate report, but not the one I was expecting:
![image](https://github.com/yhirose/cpp-peglib/assets/323009/a52b5d95-5d32-4ec8-aa7d-eeea488e523e)
(I expected the error to be that it was expecting `<Object>`)

I suspect something else is also going wrong here, because the %whitespace change doesn't affect this 3rd case:
![image](https://github.com/yhirose/cpp-peglib/assets/323009/d550d28f-5b69-4afb-84d3-7ac8c78c2e6b)

but at the same time, I get a low-quality error from the second match case:
![image](https://github.com/yhirose/cpp-peglib/assets/323009/b818349c-1792-49b8-be1d-3b3657b8eacd)
(it should be expecting `<ObjectMember>, '}'`)

whereas the original combination gives me excessive expectations:
![image](https://github.com/yhirose/cpp-peglib/assets/323009/7be31286-ceb5-4b7d-b538-c2dc9809a66e)

and this slight variation (introducing an extra component from the original grammar) confuses me the most:

![image](https://github.com/yhirose/cpp-peglib/assets/323009/95b30f88-d39b-4742-b166-c7c28881874b)

```
File <- Compound
Value <- [0-9]+
Field <- [a-z]+

%whitespace <- [ \t\r\n]*

Compound <- Unit / Array / Object

Unit <- '{' '}'
Array <- '{' (Unit/Object)+ '}'
Object <- '{' ObjectMember+ '}'
ObjectMember <- Field '=' Value ','?
```

The first '{' could be either Unit, Array, or Object. the next token, '{' eliminates unit and Object, only array allows '{' next.  So surely when it reaches the 1 it is expecting either '}' or ObjectMember->Field?

**Comment by yhirose** [comment]
The following is just a grammar error since `Unit` isn't referenced even if it declared...
![image](https://github.com/yhirose/cpp-peglib/assets/357397/04428e58-1438-4809-9dbb-2a99f512df4d)

**Comment by yhirose** [comment]
@kfsone by the way, could you split this issue to separate issues? It's pretty hard for me to follow...

**Comment by yhirose** [comment]
One issue at a time. :)

**Comment by kfsone** [comment]
It's one issue, the extra information is to show what I tried that also didn't work

**Comment by kfsone** [comment]
So the solution is to prefix the rule with _? What does _ do?

**Comment by yhirose** [comment]
@kfsone, yes, rules which start with `_` won't show up in error messages. I forgot to specify it in the README... I'll update the README.

https://github.com/yhirose/cpp-peglib/blob/d9d38ec122f450930bef3c4e7abdb60db4af20ca/peglib.h#L2598-L2599

**Comment by kfsone** [comment]
Excellent - thank you - I can close this, you've already tackled the issue :)
