### ISSUE TITLE
Severe performance regression in 1.8.6

### ISSUE THREAD

**Issue by joankaradimov** [yhirose/cpp-peglib#294]
I'm running this grammar:
https://github.com/joankaradimov/Magnetar/blob/master/MagnetarCraft/src/iscript_parser.cpp#L71
... with this input file:
https://raw.githubusercontent.com/neivv/aice/master/test_scripts/vanilla.txt

On v1.8.5 I'm observing parse times of below 1 second. On 1.8.6 it's above 10 seconds.

Similarly -- on the [web playgound](https://yhirose.github.io/cpp-peglib/) I was running identical examples for under 150 ms the previous week. I'm assuming the version over there was updated these last couple of days, since the execution times are suddenly 1-2 orders of magnitude worse.

**Comment by yhirose** [comment]
@joankaradimov I guess [this commit](https://github.com/yhirose/cpp-peglib/commit/6201458f3b685ddc93d1729893e292ded7c9c609) causes this problem. I'll take a look at it some time this weekend. Thanks for catching the serious problem!

**Comment by joankaradimov** [comment]
In that case I think it might be [this line](https://github.com/yhirose/cpp-peglib/commit/6201458f3b685ddc93d1729893e292ded7c9c609#diff-5ca9fbaaa7735ba1e069e166f23ab9553fa99963defa0cd7762b4604e8f52c5dR404). There are multiple `std::string` constructors being called within a while loop. I think this line can easily be moved outside the loop. And then the additional `std::string` allocation can be avoided altogether in the non-case-insensitive case.

Maybe something like this: https://github.com/yhirose/cpp-peglib/pull/295

**Comment by yhirose** [comment]
@joankaradimov could you check performance with the latest peglib.h in the master branch? If you confirm that it fixes the performance regression, I'll bump the version to 1.8.8. Thanks!

**Comment by joankaradimov** [comment]
@yhirose I can confirm the problem is fixed.

From ~10 seconds previously down to below 50 ms now.

**Comment by yhirose** [comment]
It's now included in v1.8.8. Thanks for your fine contribution!

**Comment by yhirose** [comment]
@joankaradimov no. I don't know who are working on vcpkg, or other package managers like conan.
