### ISSUE TITLE
The & operator is undocumented.

### ISSUE THREAD

**Issue by gamagan** [yhirose/cpp-peglib#308]
The `&` operator is undocumented.

**Comment by yhirose** [comment]
It's because the And-predicate is in the original PEG syntax described in the [document](http://www.brynosaurus.com/pub/lang/peg.pdf) by by Bryan Ford.

Please see the 4th paragraph in README. Thanks.

**Comment by gamagan** [comment]
It would be helpful to document the original PEG operators on the page, for completeness. A quick mention could remind the users they exist. Something like:

---

The PEG syntax is well described on page 2 in the [document](http://www.brynosaurus.com/pub/lang/peg.pdf) by Bryan Ford. 
cpp-peglib supports the original operators:


- `' ' ` (Literal string)
- `" "`  (Literal string)
- `[ ]`  (Character class)
- `.`  (Any character)
- `(e)`  (Grouping)
- `e?`  (Optional)
- `e*`  (Zero-or-more)
- `e+`  (One-or-more)
- `&e` (And-predicate)
- `!e`  (Not-predicate)
- `e1 e2` (Sequence)
- `e1 / e2` (Prioritized Choice)


cpp-peglib also supports the following additional syntax for now:
