### ISSUE TITLE
make 'release' tag?

### ISSUE THREAD

**Issue by easz** [yhirose/cpp-peglib#31]
just want to know if you are going to make some 'release' or 'tag' on this project?
I assume the code is pretty stable enough..

**Comment by yhirose** [comment]
@easz, thanks for the suggestion. I'll think about it.
Since I have other head-only cpp libraries such as 'cpp-httlib', I'll try to come up with a consistent way among the 'cpp-' familiy.

**Comment by yhirose** [comment]
I'll reopen it when I found a good solution which can work for all the 'cpp-' libraries.
