### ISSUE TITLE
Crash when using rules and ast together

### ISSUE THREAD

**Issue by gamagan** [yhirose/cpp-peglib#310]
I'm not sure if it's something that I'm doing wrong but, from my vantage point, I don't see an issue with my code.

cpp-peglib crashes if I define an action on a rule, plus another action on a child rule, and also enable ast.

It does not crash if I don't `parser.enable_ast()`.

If crashes with a `bad_any_cast`, at this location:

```
  // Transform the semantic value vector to another vector
  template <typename T>
  std::vector<T> transform(size_t beg = 0,
                           size_t end = static_cast<size_t>(-1)) const {
    std::vector<T> r;
    end = (std::min)(end, size());
    for (size_t i = beg; i < end; i++) {
      r.emplace_back(std::any_cast<T>((*this)[i]));  // HERE
    }
    return r;
  }
```

**Comment by yhirose** [comment]
@gamagan thanks for the info, but it's too little information to investigate...

**Comment by yhirose** [comment]
@gamagan please check with examples which uses the ast mode in `/example` and `/test` folder.
