### ISSUE TITLE
Segmentation Fault with user defined rule

### ISSUE THREAD

**Issue by ydaveluy** [yhirose/cpp-peglib#311]
Hello,

I noticed that the test  [UserRuleTest.User_defined_rule_test](https://github.com/yhirose/cpp-peglib/blob/2ab5d27d7b866b210c52ee2718f00ef202da173a/test/test2.cc#L816) crash with a segmentation fault.

The problem is hidden when running the test with ctest and appears when executing `build/test/peglib-test-main` directly.

The segfault appears because ope.ope_ is null : https://github.com/yhirose/cpp-peglib/blob/2ab5d27d7b866b210c52ee2718f00ef202da173a/peglib.h#L2062

**Comment by yhirose** [comment]
@ydaveluy thanks for your report!
