### ISSUE TITLE
how can I incremental tal parse using cpppeglib

### ISSUE THREAD

**Issue by sunshine725** [yhirose/cpp-peglib#312]
Hi!
I have a syntax like java.peg in you readme
# java.peg
```
Prog        ← 'public' 'class' NAME '{' 'public' 'static' 'void' 'main' '(' 'String' '[' ']' NAME ')' BlockStmt '}'
BlockStmt   ← '{' (!'}' Stmt^stmtb)* '}' # Annotated with `stmtb`
Stmt        ← IfStmt / WhileStmt / PrintStmt / DecStmt / AssignStmt / BlockStmt
IfStmt      ← 'if' '(' Exp ')' Stmt* ('else' Stmt*)? 'endif'
WhileStmt   ← 'while' '(' Exp')' Stmt* 'endwhile'
DecStmt     ← 'int' NAME ('=' Exp)? ';'
AssignStmt  ← NAME '=' Exp ';'^semia 
PrintStmt   ← 'System.out.println' '(' Exp ')' ';'
Exp         ← RelExp ('==' RelExp)*
RelExp      ← AddExp ('<' AddExp)*
AddExp      ← MulExp (('+' / '-') MulExp)*
MulExp      ← AtomExp (('*' / '/') AtomExp)*
AtomExp     ← '(' Exp ')' / NUMBER / NAME

NUMBER      ← < [0-9]+ >
NAME        ← < [a-zA-Z_][a-zA-Z_0-9]* >

%whitespace ← [ \t\n]*
%word       ← NAME
```

my question is that since my prog is large,when I parse the whole prog, it may use a lot of time, I wonder can I parser the prog file every 50 lines, As I have IfStmt /WhileStmt cycle which more than one line, if the 50th line is in cycle,it may parse error, how can I save the right lines and record the error cycle begin ,then I can parse next time, if you have another idea can solve my problem?thanks!

**Comment by yhirose** [comment]
Thanks for your question, but I actually don't know an answer if it's really possible. (I doubt you can do it though.) Sorry about that...
