### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by friol** [yhirose/cpp-peglib#317]
Hello, I'm using cpp-peglib in my own intepreter (https://github.com/friol/liaison).

Two questions:

1. I am generating the AST after parsing the source code. After successfully parsing the code, each node in the generated AST has a "name" property (like "StringLiteral", etc.). Then, in the interpreter, I do a lot of "ifs" that are string comparisons, like "if (nodeName=="StringLiteral"). Is there a way, instead, to tag each node with (for example) a number or an enum, so identifying the node type would be faster than string comparison?

2. Is there a way to remove unuseful elements (like comments, multi-line comments, etc.) from the AST?

Thanks

**Comment by yhirose** [comment]
@friol really good questions!

Here is my answer:
1. `tag`  member variable in a AST node (This member variable is a hash value for the name.)
https://github.com/yhirose/culebra/blob/c238c940119daa2a6c575564f2d6c1954119d124/include/interpreter.h#L603-L608

2. `~` (ignore operator)
https://github.com/yhirose/culebra/blob/c238c940119daa2a6c575564f2d6c1954119d124/include/interpreter.h#L85-L87

Hope it helps!
