### ISSUE TITLE
Handling comments?

### ISSUE THREAD

**Issue by g40** [yhirose/cpp-peglib#32]
Hi Yuji

Any thoughts on the best way to handle single line comments, C++ or Python style? 

```
// I am a comment
# ditto
```

Not sure if this can be easily done in a grammar. Wondering if there could be a `%comment` directive as per `%whitespace`

I had forgotten how utterly cool this code is for writing parsers. 👍

**Comment by yhirose** [comment]
@g40, thanks for the feedback. I actually handled the single line comment in [my experimental programming language](https://github.com/yhirose/culebra).

Here is [the rule snippet](https://github.com/yhirose/culebra/blob/master/misc/culebra.peg#L78-L87) that handles the line comment:

```
End                      <-  EndOfLine / EndOfFile
EndOfLine                <-  '\r\n' / '\n' / '\r'
EndOfFile                <-  !.
LineComment              <-  ('#' / '//') (!End .)* &End
```
This is a sample code that uses line comments.
https://github.com/yhirose/culebra/blob/master/samples/bug.cul

Does it work for you as well?

**Comment by g40** [comment]
Hi Yuji

Thanks. Yes, I saw that in the grammar grammar. My problem is that one now has to embed whitespace rules in the grammar which can be problematic, esp. in more complex cases.  What I had in mind was abstracting the parser data source

```
template <typename T=char>
class data_source
{
// set up data source
data_source(const T* ps,size_t count) { ... }
//
T next() { // return next character }
// how many chars were matched?
size_t size() const { ... }
// reset data source if match failed
void reset() {... }
// once matched, i.e. '#' or '//' skips until eol
comment_mode(const char* ps) {...}
// multi-line, match start, continue to end ...
comment_mode(const T* ps,const T* pe) {...}
};
```
This is pretty non-invasive, just one level of indirection:
```
         std::string example("# hello world");
        data_source<> ds(example.data(),example.size()));
        ds.comment("#");
	std::shared_ptr<peg::Ast> ast;
	if (!parser.parse_n(ds.data(), ds.size(), ast))
             throw "an error!";
```
Thoughts?

BR

Jerry.

**Comment by yhirose** [comment]
HI Jerry, sorry for the late reply. I think the data source shouldn't have any 'parsing' logic like comment skipping, so that all rules can be seen in a PEG grammar file. I just wonder how difficult to specify your comment syntax in PEG grammar?

**Comment by g40** [comment]
Hi Yuji,

Sorry for the late reply here. On reflection, I think you are right. The `lex` style comment parsing mechanism does not work well with PEG parsers ...

Best.
