### ISSUE TITLE
Semantic Values seems weird if string and string are nearby

### ISSUE THREAD

**Issue by chumicat** [yhirose/cpp-peglib#35]
I would better to use less code to complain the problem that I had occurred.
For example the parser expressions are as below:
```
ASSIGN			<-	"Set" TYPE IDSTR '=' EXPRESSION
TYPE			<-	["Interger""Decimal"]
IDSTR			<-	[_A-Za-z][_A-Za-z0-9]*
 EXPRESSION		<-	...brabrabra, just return double value...
```
And I want to parse "SetDecimalvariable=50.0"
sv that I get in ASSIGN will be as follow:
> ```
> sv.size() == 3        // fine, (TYPE, IDSTR, EXPRESSION) are three element
> sv.str_c() == "SetDecimalvariable=50.0"        // fine, originally data
> sv[0].get<string>() == "Decimalvariable=50.0"        // weired, it should be "Decimal" as first element
> sv[1].get<string>() == "ecimalvariable=50.0"        // more weired, it should be "variable" as second element
> sv[2].get<Ele>() == 50.0        // fine, it's the third element
> ```
Am I thought wrong?
Thanks for the project, it helps me a lot.

**Comment by yhirose** [comment]
@chumicat, please see the following code. 

```cpp
    peg::parser parser(R"(
ASSIGN			<-	"Set" TYPE IDSTR '=' EXPRESSION
TYPE			<-	"Interger" / "Decimal"
IDSTR			<-	[_A-Za-z][_A-Za-z0-9]*
EXPRESSION		<-	[0-9]+ ("." [0-9]+)?
    )");

    parser["ASSIGN"] = [&](const peg::SemanticValues& sv) {
        std::cout << sv.size() << std::endl;
        std::cout << sv.c_str() << std::endl;
        std::cout << sv[0].get<string>() << std::endl;
        std::cout << sv[1].get<string>() << std::endl;
        std::cout << sv[2].get<string>() << std::endl;
    };

    parser["TYPE"] = [&](const peg::SemanticValues& sv) {
        return sv.token();
    };

    parser["IDSTR"] = [&](const peg::SemanticValues& sv) {
        return sv.token();
    };

    parser["EXPRESSION"] = [&](const peg::SemanticValues& sv) {
        return sv.token();
    };

    auto ret = parser.parse("SetDecimalvariable=50.0");
```

Results:
```
3
SetDecimalvariable=50.0
Decimal
variable
50.0
```

Hope it helps.

**Comment by chumicat** [comment]
Thanks. It seems that I return the wrong type since it needs to return token but I return string type.
