### ISSUE TITLE
Allow peglib to work w/o RTTI

### ISSUE THREAD

**Issue by mmastrac** [yhirose/cpp-peglib#36]
The current library is pretty close to working without C++ RTTI being enabled. peglib is useful for environments where RTTI adds more space/time overhead than is acceptable, but it currently requires some very minor changes to the code (ie: `#ifdef __cpp_rtti` around the uses of `dynamic_cast` and replacement methods that return `void*` instead).

Would this be something that you'd be OK accepting a patch for?

**Comment by yhirose** [comment]
@mmastrac, thanks for the feedback. As long as the interface stays as it is, I am fine with the change. Could you send a pull request for the change, so that I could take a look at it? Thanks!

**Comment by yhirose** [comment]
@mmastrac, please let me know when you are ready to send the pull request. I'll reopen this issue then.
