### ISSUE TITLE
C/C++ escaped quotes in strings?

### ISSUE THREAD

**Issue by g40** [yhirose/cpp-peglib#4]
Hello Yuji.

Cannot get this to work using master. The intention is to be able to parse a C/C++ style literal string with escaped quotes as in:

```
// i.e. file content, not a compiled string
" Hello \"Yuji\" "
```

Any thoughts? The rule is specified this:

```
// 
RULE <- '"' (LITERAL_ESC_QUOTE / LITERAL_CHAR)* '"'
// i.e. match anything that is not a single quote character
LITERAL_CHAR <- (!["] .)
// this is a string not an escaped quote
LITERAL_ESC_QUOTE  <- '\"'
```

TAIA.

Jerry

**Comment by yhirose** [comment]
Hi Jerry,

I guess you can simply add another backslash to make the example work.

```
LITERAL_ESC_QUOTE  <- '\\"'
```

Is it what you expected?

Hope this helps.
Yuji

P.S. You can try it on my online peglint at http://yhirose.github.io/peglint/. (It sometimes down thought...)
Also the command-line version of [peglint](https://github.com/yhirose/cpp-peglib/blob/master/lint/cmdline/peglint.cc) is very useful to me. You can easily build it.

**Comment by g40** [comment]
Hello Yuji. Thank you. That does indeed work. 
```
// C string style escapes (hex and friends to come)
RULE <- '"' (ESC_QUOTE / LIT_CHAR)* '"'
LIT_CHAR <- (!["] .)
ESC_QUOTE  <- ('\\"' / '\\t' / '\\n')
```
```
 => "Hello \"J\" \t \" K \" \n " pass
```
Odd. I must have tested that variety a good number of times.
