### ISSUE TITLE
Simple grammar failing

### ISSUE THREAD

**Issue by dail8859** [yhirose/cpp-peglib#51]
I hate opening GitHub issues simply asking for help, however I've been fighting with a seemly simple grammar that I've not been able to get working correctly. I stumbled across peglint for testing luckily.

File `a.peg` contains:

```
Any         <- Placeholder / Text
Placeholder <- '${' Int ':' Any '}'
Int         <- [0-9]+
Text        <- [a-z]+
```

Running a simple example works as expected:

    > peglint.exe --ast --source "${1:hi}" a.peg
    + Any
      + Placeholder
        - Int (1)
        + Any
          - Text (hi)

A bit more complex example doesn't work:

    > peglint.exe --ast --source "${1:hi${2:bye}}" a.peg
    [commendline]:1:7: syntax error

I'm using Win7 and VS2015 if that makes a difference at all. Thanks.

**Comment by yhirose** [comment]
@dail8859, thanks for using this library!

After the parser recognizes `${1:`, it tries to find `Any`. `Any` doesn't match `hi${2:bye}`, but just `hi`. Then the parser tries to find `'}'`, but finds `$`. So this example failed.

If we want to allow mixed content of `Placeholder` and `Text` for `Any`, the `Any` definition could be like this:

```
Any         <- (Placeholder / Text)+ 
```

Here is my result with the modified PEG grammar.

```
+ Any
  + Placeholder
    - Int (1)
    + Any
      - Text (hi)
      + Placeholder
        - Int (2)
        + Any
          - Text (bye)
```

Does the above change work for you?

**Comment by dail8859** [comment]
@yhirose thanks for the quick response.

Yes that works perfectly and I see what I was doing wrong now.

Keep up the great work.
