### ISSUE TITLE
peglint example crashes

### ISSUE THREAD

**Issue by yesint** [yhirose/cpp-peglib#59]
peglint exits with an error when trying to reproduce tutorial example:

```
./peglint --ast --opt --source "1 + 2 * 3" a.peg
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
```

Seems to be a regression of #46 

My environment is: Linux Mint 19.1, gcc 7.3.0.

**Comment by yhirose** [comment]
@yesint, thanks for the report. As you see #46, what I did at #46 is just linking pthread library on Linux environment, no code change in peglib.h at all. Could you make sure that the pthread is linked to your executable file? Thanks for your help!

**Comment by yhirose** [comment]
@yesint, please let me know if it still happens with the pthread linked.
