### ISSUE TITLE
Capture and AST generation

### ISSUE THREAD

**Issue by g40** [yhirose/cpp-peglib#6]
Hi Yuji, would be very interested to get your thoughts on this too.

1. parser fills the ast.token value with the literal content of the string.
```
STRING_LITERAL	<- < '"' (('\\"' / '\\t' / '\\n') / (!["] .))* '"' > 
```

2. no capture, ast.token value is empty.
```
STRING_LITERAL	<- '"' (('\\"' / '\\t' / '\\n') / (!["] .))* '"' 
```
3. parser creates an AST node for  STRING_LITERAL with a new child leaf for each matching occurrence of ESC and CHAR. Obviously there is no content in the AST token member.
```
STRING_LITERAL	<- < '"' (ESC / CHAR)* '"' > 
ESC                                <- ('\\"' / '\\t' / '\\n')
CHAR                             <- (!["] .)
```

Questions: 
Are the differences in 1 and 2 intentional?
3 is possibly unexpected but is consistent throughout so not a problem. I think this definitely worth documenting in readme.

**Comment by yhirose** [comment]
Hi Jerry,

I have checked 2 and 3. Please see three unit tests that I just added at 49c81a5f59a3fd789a0ef74e3b6f3c52ec288406. All tests passed successfully. It seems like the results are what you expect. Let me know if I misunderstand what you meant with the above comment.

Thank you,
Yuji

**Comment by g40** [comment]
Thanks. That is all as I expected.
