### ISSUE TITLE
left recursion not detected

### ISSUE THREAD

**Issue by mqnc** [yhirose/cpp-peglib#63]
Hi Yuji!

I stumbled upon an undetected left recursion. It was hiding deep down in my grammar and I was able to reduce it to the following pattern:
```
_ <- ' '*
A <- B
B <- _ A
```
Peglib/Peglint does not see a problem there. However, if I substitute the _ rule, it works fine:
```
A <- B
B <- ' '* A
```
```
lrec.peg:1:6: 'B' is left recursive.
lrec.peg:2:11: 'A' is left recursive.
```

**Comment by yhirose** [comment]
@mqnc, thanks for tracking down the bug and making the minimal example! I'll look into it.

**Comment by yhirose** [comment]
@mqnc, I fixed it. Please let me know if the latest peglib.h works on your environment. Thanks for your contribution!

**Comment by mqnc** [comment]
Tried it, works! Fixed in less than a day. Always a pleasure to open source with you :)
