### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by MoAlyousef** [yhirose/cpp-peglib#64]
Hello
Great library.
It would be great if you had official releases of cpp-peglib even if it's only a header only library, it would make packaging and versioning possible with vcpkg and/or conan, even with cmake fetchcontent which fetches content by git tags. 
Thank you for your consideration.

**Comment by yhirose** [comment]
@MoAlyousef, thanks for the suggestion. I tagged the latest commit with `v0.1.0`.

**Comment by MoAlyousef** [comment]
Thanks.
https://github.com/microsoft/vcpkg/pull/7254
