### ISSUE TITLE
Token boundary operators

### ISSUE THREAD

**Issue by zomgrolf** [yhirose/cpp-peglib#68]
I'm trying to wrap my head around how token boundary operators work. The docs offer a few examples, but do not specify exactly how token boundary operators behave or where there may appear in the grammar. I would greatly appreciate some additional clarification as to what exactly they're supposed to do (and how). Sometimes, I find it difficult to predict what effect using a token boundary operator will have or whether I should use it or not, because my mental model of token operators clearly has some gaps. I had a quick look at the source code and the parsing function seems to parse whatever expresion is contained by the token boundary operator, and then, if there's a whitespace parser present, it tries to parse any whitespace that follows already parsed expression. But, clearly, there is more to it, as can be easily observed:

Consider the following grammar:
```C++
auto grammar = R"(
    START       <- A? B+ C?
    A           <- A_ID NUMBER
    B           <- B_ID NUMBER
    C           <- C_ID NUMBER
    A_ID        <- <'a'>
    B_ID        <- <'b'>
    C_ID        <- <'c'>
    NUMBER      <- < [0-9]+ >
    %whitespace <- [ \t\r\n]*
)";
```
and the following program that uses the grammar above to parse a simple string:
```C++
int main()
{
    peg::parser parser(grammar);
    string input_string = "a 1 b 2 b 3 c 4";

    parser.enable_ast();
    shared_ptr<peg::Ast> ast;

    if (parser.parse(input_string.c_str(), ast)) {
        cout << peg::ast_to_s(ast) << "\n";
    }
    return 0;
}
```
The output it prints is more or less what I would expect:
```
+ START
  + A
    - A_ID (a)
    - NUMBER (1)
  + B
    - B_ID (b)
    - NUMBER (2)
  + B
    - B_ID (b)
    - NUMBER (3)
  + C
    - C_ID (c)
    - NUMBER (4)
```
Now, if I modify the grammar slightly, to eliminate the rules for identifiers:
```C++
auto grammar2 = R"(
    START       <- A? B+ C?
    A           <- <'a'> NUMBER
    B           <- <'b'> NUMBER
    C           <- <'c'> NUMBER
    NUMBER      <- < [0-9]+ >
    %whitespace <- [ \t\r\n]*
)";
```
it produces a different AST (obviously!), but it's different in some surprising ways:
```
+ START
  - A (a)
  - B (b)
  - B (b)
  - C (c)
```
I would perhaps expect something closer to what I get with the following grammar:
```C++
auto grammar3 = R"(
    START       <- A? B+ C?
    A           <- 'a' _ NUMBER
    B           <- 'b' _ NUMBER
    C           <- 'c' _ NUMBER
    NUMBER      <- < [0-9]+ >
    ~_          <- [ \t\r\n]*
    %whitespace <- [ \t\r\n]*
)";
```
which is:
```
+ START
  + A
    - NUMBER (1)
  + B
    - NUMBER (2)
  + B
    - NUMBER (3)
  + C
    - NUMBER (4)
```
Is the token boundary operator meant to have an effect on how the AST is built? How about semantic values passed to semantic actions for rules that contain token boundary operators?

**Comment by zomgrolf** [comment]
I've noticed some surprising (to me) behavior when trying to use this operator in some slightly more complicated rules, e.g.:
```C++
auto grammar4 = R"(
    START   <- < 'abc' > / DEF GHJ
    DEF     <- < 'def' >
    GHJ     <- < 'ghj' >
    %whitespace <- [ \t\r\n]*
)";
```
trying to match the following: `string input_string = "def    ghj    ";`, produces:
```
- START/1 (def    ghj    )
```
If I modify the grammar:
```C++
auto grammar5 = R"(
    START   <- 'abc' / DEF GHJ
    DEF     <- < 'def' >
    GHJ     <- < 'ghj' >
    %whitespace <- [ \t\r\n]*
)";
```
and try to match the same string, I get:
```
+ START/1
  - DEF (def)
  - GHJ (ghj)
```
which is what I would expect.

**Comment by ThomasKrenn** [comment]
I believe the token boundary operator just tells the parser not to store other parts of the rule. 
(Or: The interesting part is inside the angle brackets.)
The LINES rule in my example only keeps the text but not the line numbers at the beginning of the line.

```
START  <- A '\n' B '\n' C '\n' LINES*
A      <- 'aa' <'bb'>
B      <- <'aa'> 'bb'
C      <-  'aa'  'bb'
LINES  <- [0-9]+ ' ' <[0-9a-zA-Z ]*> '\n'*
```

```
aabb
aabb
aabb
01 ABC
02 More lines
```
AST:

```
+ START
  - A (bb)
  - B (aa)
  - C (aabb)
  - LINES (ABC)
  - LINES (More lines)
```
How the boundary operator works together with %whitespace is a another story.
Inside the boundary %whitespace does not work! That is what the documentation tries to explain.

```
START  <- A B C D
A      <- 'aa' <'bb'>
B      <- <'aa'> 'bb'
C      <- 'aa' 'bb'
D      <- <'aa' 'bb'>
%whitespace <- [ \t\r\n]*
```

```
aa bb
aa bb
aa bb
aabb
```
If rule D is 'aa bb', it will not parse.
Hope this helps.

**Comment by zomgrolf** [comment]
Thanks! That makes much more sense. And it matches the name of the operator way better. Somehow I got the impression that it was needed to make the whitespace skipping work. And debugging the token parsing function shows that the whitespace parser does get invoked, if present, after parsing the bounded expression.
```
    START   <- 'abc' / DEF GHJ
    DEF     <- 'def'
    GHJ     <- 'ghj'
    %whitespace <- [ \t\r\n]*
```
trying to parse this: "def    ghj    ", produces the following AST:
```
+ START/1
  - DEF (def    )
  - GHJ (ghj    )
```
so, `%whitespace` is clearly not sufficient on its own...

That still leaves the question, why the difference between results produced by grammar 4 and 5 in my example above (it stores DEF GHJ, just stores them with the following whitespace characters).

**Comment by yhirose** [comment]
@ThomasKrenn, thanks for the excellent explanation!

@zomgrolf, when it comes to the grammar 4, `START` is incorrectly recognized as a token node because the rule includes a token operator. That's why the ast printer stops at the `START`. I may be able to fix it by adjusting the logic in `TokenChecker` visitor class. As for `DEF (def    )` and `GHJ (ghj    )` in the last example,  I'll look into the code. Thanks for your feedback!

**Comment by zomgrolf** [comment]
Awesome, thanks! I've tested the last example and it indeed behaves how I would expect it to behave.
