### ISSUE TITLE
peglib is not threadsafe

### ISSUE THREAD

**Issue by toddlipcon** [yhirose/cpp-peglib#84]
Because parse_core visits all of the definitions in a grammar to assign IDs, a single grammar cannot be used by multiple threads concurrently, even if the parser object has been cloned. It seems like this could be solved if the visitor were applied as part of the grammar constructor instead of inside parse_core.

**Comment by yhirose** [comment]
@toddlipcon, thanks for the feedback. Please let me know if you have any suspicious things with my fix.
