### ISSUE TITLE
AST does not save if optionals are used 

### ISSUE THREAD

**Issue by manuelliebchen** [yhirose/cpp-peglib#92]
Hey,
so I'm trying to extract if an option has bin used that does not create an extra ast node.
Something like that:
```
A <- <[a-z]*> '*'?
```
And so I want to have an option to know if there is a '*' at the end in the ast?
This is just a minimal example, where in my project the gramma can also have an '*' token after the A.
I hope I'm not just to blind to see this but the AstBase does not seem to have this in it.

**Comment by yhirose** [comment]
@manuelliebchen, although I probably don't fully understand what you are talking about, you may want to try the following grammar.

```
A        <- TOKEN ASTERISK?
TOKEN    <- <[a-z]*>
ASTERISK <- '*'
```

If you parse `work*` with the above grammar, you will get the following AST tree:

```
+ A
  - TOKEN (work)
  - ASTERISK (*)
```

If you parse `work` with the above grammar, you will get the following AST tree:

```
+ A
  - TOKEN (work)
```

So, you can know the condition by checking if `ASTERISK` child node exists in `A` node.

Hope it helps!

**Comment by manuelliebchen** [comment]
@yhirose Thanks for the quick answer, that's also what I came up with as a workaround.
