### ISSUE TITLE
curly braces for min and max number of occurrences

### ISSUE THREAD

**Issue by Quetzalfir** [yhirose/cpp-peglib#95]
Does the library have a syntactic way of writing a minimum and maximum number of occurrences?

`OCURRENCES  <- NUMBER{1,3}`
`NUMBER      <- ('+'|'-')? [0-9]+`

I understand that this is possible in PEG.
I have used the library and I really like it, it would be great if it had this functionality

**Comment by yhirose** [comment]
@Quetzalfir, the original Bryan Ford's PEG syntax doesn't have it. I agree that it's useful to provide the Regex-like {min,max} repetition syntax as an enhanced syntax.

But unfortunately, `{` and `}` are already used to provide special instruction to a definition rule in cpp-peglib. Although cpp-peglib currently uses it only for 'parsing infix expression' support, I am thinking to make more instructions in the future to enhance the cpp-peglib functionality. So if we want to introduce the {min,max} repetition syntax, we have to change the current cpp-peglib PEG syntax. Also I am actually using this 'parsing infix expression' feature in my project...

I'll ponder how to implement it without making a breaking change to the current PEG syntax.
Anyway, thanks for your suggestion!

**Comment by Quetzalfir** [comment]
This project currently is very nice but it also has a lot of opportunities of enhancement.

I've not seen the source code yet, but it seems that it already has the syntax opportunity, since in the grammar you have to put the word "precedence", detecting that, it could switch into several cases.

It also would be great to also see other functionalities as including a grammar into other one, see other “syntactic sugars" as:


`&& | Double ampersand | Components are mandatory but may appear in any order | <length> && <string>`


`|| | Double bar | At least one of the components must be present, and they may appear in any order. | <length> || <string>`


Currently I'm in a full time project, in which I use this library, but I'm really interested in this. When I finish my project I could help with this.

Good work!

**Comment by yhirose** [comment]
@Quetzalfir, I implemented the regex-like repetition operator.

**Comment by Quetzalfir** [comment]
nice, really appreciate it

**Comment by yhirose** [comment]
Examples:

https://github.com/yhirose/cpp-peglib/blob/95f91404640ddbd21e7ea68c2650a90636f25f3d/test/test2.cc#L479-L537
