### ISSUE TITLE
Have  the rules of the asset files name  been changed?

### ISSUE THREAD

**Issue by toge** [yhirose/cpp-peglib#96]
Thank you for your continued release.I love this library.

I have one question.
In  0.1.6 release, I think the rules for the asset files name have been changed.
```
0.1.6 : https://github.com/yhirose/cpp-peglib/archive/0.1.6.zip
0.1.5 : https://github.com/yhirose/cpp-peglib/archive/v0.1.5.zip
```
Please tell me if this is intentional?

**Comment by yhirose** [comment]
@toge, good catch! I corrected it. It should be good now. Thanks!
